### ISSUE TITLE
Can't start TWS.

### ISSUE THREAD

**Issue by huangjqiu** [ib-controller/ib-controller#100]
Hello,
Not sure if I should ask the question here. My apologies. It might not be IBcontroller related issue. I started IBcontroller, but it couldn't start TWS. 

I followed the install instruction on an instance on google clould with Debian 8. I configured the desktop using XFCE and VNC. I can see the desktop without problem with VNC viewer remotely. The TWS is stable 952 version. 

When I use the command to start IBController, the TWS Window never appears.
$ sudo bash /opt/IBController/IBControllerStart.sh
I am using a user other than root. It seems the display is at issue. Here is the Log file:

`13:43:13:202 IBController: using default settings provider: ini file is /home/vnc/IBController/IBController.ini
13:43:13:203 IBController: using default login manager: getting username and password from args but not found. Will get from settings
13:43:13:203 IBController: using default config dialog manager: constructor parameter isGateway=false
13:43:13:205 IBController: using default trading mode manager: constructor parameter args but trading mode not present - will be taken from settings
13:43:13:208 IBController: using default config dialog manager
13:43:13:217 IBController: IBControllerServer is started.
13:43:13:348 IBController: IBControllerServer listening on address: ib/10.142.0.2 port: 7462
Client is not authorized to connect to ServerException in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':1.0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
        at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:126)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.Toolkit$2.run(Toolkit.java:860)
        at java.awt.Toolkit$2.run(Toolkit.java:855)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
        at ibcontroller.IBController.createToolkitListener(Unknown Source)
        at ibcontroller.IBController.load(Unknown Source)
        at ibcontroller.IBController.main(Unknown Source)

================================================================================
`
How can I fix this problem?

Any help would be greatly appreciated.

**Comment by shevkoplyas** [comment]
hi there,

the key to the problem is this line  "Client is not authorized to connect
to ServerException in thread "main" java.awt.AWTError: Can't connect to X11
window server using ':1.0' as the value of the DISPLAY variable"

So basically IBController can't connect to your X11. Check your $DISPLAY
environment is set properly.
Most probably it should be DISPLAY=:0 (you can also sneak peak what should
be your DISPLAY from your VNC process command-line or environment (if VNC
is working fine as you said))

instead of your start command:
$ sudo bash /opt/IBController/IBControllerStart.sh

try following:

$ sudo su -l
# chmod a+x /opt/IBController/IBControllerStart.sh
# DISPLAY=:0  /opt/IBController/IBControllerStart.sh

You probably will find useful systemd files to auto-start IBController +
VNC from here even though it is for Ubunt, but Debian 8 switched to systemd
as default init system as well as Ubuntu 16.04):

How to setup IBController (3.2.0) + TWS (build 956) on headless Ubuntu
16.04 LTS to run TWO accounts (paper + real) in 10 minutes
<https://goo.gl/QPdWLW>

good luck

-- 
с ч.гл.ув.,
Дима Ш.

Dmitry's
<https://docs.google.com/document/d/1gLGdySacvdCrj2XKsf1ufvwxeMjb0LICM7ah05CMefw/pub>
TWS API FAQ <http://goo.gl/TRkeRK>

**Comment by huangjqiu** [comment]
@shevkoplyas 

Thanks for your response.

I changed the DISPLAY to 0 and tried the command line:

$ sudo su -l
# chmod a+x /opt/IBController/IBControllerStart.sh
# DISPLAY=:0  /opt/IBController/IBControllerStart.sh

But the problem persists.

Client is not authorized to connect to ServerException in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.

The above is the new error message.

![image](https://cloud.githubusercontent.com/assets/19940818/16150734/e9258020-3466-11e6-8a4f-1f1ce0d23c5d.png)

Attached is the screenshot of the remote desktop with the TWS I started manually. The front window is the error message after I ran IBController.

**Comment by huangjqiu** [comment]
I believe this is part of the solution--I have to do all the following lines with root:
$ sudo su -l
$ vncserver
$ chmod a+x /opt/IBController/IBControllerStart.sh
$ DISPLAY=:0 /opt/IBController/IBControllerStart.sh

The TWS will be started. In this way the IBController ini should be put in the root folder if it is encrypted.

The problem is that using root may expose risk and Google cloud uses the email address as the default user with Debian 8.

Is there any better solution that we can use the default user other than root?

Any help would be greatly appreciated.

**Comment by rlktradewright** [comment]
There is absolutely nothing about IBController that requires it to be run under root. I'm sure that the same applies to vncserver. So I don't understand why you're using sudo at all. Provided your non-root user has execute access to IBController (and TWS), and has write access to the log file directory, everything should just work.

**Comment by huangjqiu** [comment]
@rlktradewright 

Yes, you are right. I messed up with sudo. Everything works fine without sudo.

Thank you very much for your help.
