### ISSUE TITLE
How to setup IBController with latest TWS API and IB Gateway? 

### ISSUE THREAD

**Issue by oemGitHub** [ib-controller/ib-controller#121]
After downloading the latest TWS API and IB Gateway, I manually login and download data with no problem through Twsdll.xls file, but when I copy the IBController into new PC, it cannot login by running sampleIBControllerGatewayStart.bat. Please see following linked image for error details.

Does anyone have any suggestions?
Thanks in advance for any suggestions

http://i1093.photobucket.com/albums/i438/junk000/IB_Error_zpshcerv4i1.png

**Comment by rlktradewright** [comment]
As I told you when you posted the same question on the TWSAPI group, you haven't set either TWS or IBController up properly. I suggested you should go and read the user guide, and make sure you're using the offline version of TWS/Gateway. That advice still applies.

By the way, it would be much more sensible to post the IBController log file rather than a screen shot that really shows nothing apart from the fact that things aren't set up right.

You mention sampleIBControllerGatewayStart.bat: there is no such file in the IBController download, so are you sure you're using the latest version? Actually looking again at your screenshot, I can see that you're NOT using the latest version: the one you're using is at least three years old, and the world has changed completely since then.

So do yourself a favour and download the latest release from here, and start again!

**Comment by oemGitHub** [comment]
It is nice to download the latest IB Controller, could you please tell me on where to download a copy.

Furthermore, from my old computer, the old version of IB Controller still run OK with old TWS/Gateway.  from my new computer, the same old version of IB Controller (copied from old computer) is not working, could you please tell me on where to locate the setup file? so I can check on which setting are needed to be changed for the latest TWS/Gateway setup.

Do you have any suggestions?
Thank you very much for any suggestions :>

**Comment by oemGitHub** [comment]
After installing the latest Offline TWS and IB Gateway (32 bit), I run IBControllerGatewayStart and get error: TWS version 952 is not installed.  I would like to know on where to download TWS 952 instead of latest TWS version?

Do you have any suggestions?
Thank you very much for any suggestions :>
