### ISSUE TITLE
Not going beyond the API settings 

### ISSUE THREAD

**Issue by shakti-vyjayanthi** [ib-controller/ib-controller#125]
I was trying to start IBController automatically, but it gets stuck in thw API settings page. Is it to do with some settings?

**Comment by rlktradewright** [comment]
Er, let's see now ... what information have you given us that might enable us to have some idea about what the problem is?

TWS/Gateway version number? No.
IBController version number? No.
IBController log file? No.
Changes you've made to IBController.ini? No.
Windows or Linux? No.
Screenshot showing what happens? No.
Information about how you were trying to start it automatically? No.
Whether it works when you try and start it manually? No.
Live, paper or demo account? No.

Well that's not a lot to go on.

Sorry if I sound a bit sarcastic, but if you give us absolutely no information what sort of a reply do you expect?

**Comment by shakti-vyjayanthi** [comment]
I apologize for the lack of information. 

I am using IBGateway 960, with IBController version is 3.2.0. I assign the port number to the ForceTwsApiPort, the username and password, the trading mode which for this user is live, the ExistingSessionDetectedAction is primary. the AcceptIncomingConnectionAction is accept. We are trying to run this in linux. 

I have written a java code which runs shell scripts which replaces the username, password and port in the .ini file. It works when I do it manually. 

It gets stuck in the place as shown in the screenshot 

![screenshot from 2016-12-21 10-12-54](https://cloud.githubusercontent.com/assets/17611599/21377682/6e999dda-c766-11e6-873f-069826db92bc.png)

**Comment by rlktradewright** [comment]
Thanks for the extra info, it makes all the difference!

The reason it's just sitting there at the configuration dialog is that your config dialog has a title that IBController doesn't recognise, so it's not aware that this actually is the dialog in which it should be setting your API port number, so it's just waiting for a dialog to appear that conforms to its expectations.

So my question is, how come your config dialog is entitled 'Kristal Configuration' when every other config dialog I've ever seen has a title like "<account id> Trader Workstation Configuration".

Clearly I can change the way IBController recognises the config dialog (by just looking for 'Configuration' in the title), but first I want to understand why yours is different, in case this is the tip of some new iceberg that IB has floated into our path (it happens...).

**Comment by shakti-vyjayanthi** [comment]
There is a concept of White branding TWS for advisors, and we have done that, because of which the name appears like that, Is it possible the change the way you recognize the config?

**Comment by rlktradewright** [comment]
Ah, right, learn something new every day.

Yes, I can change the recognition criteria. The only negative is that we've now only got the single word 'Configuration' to indicate the config dialog, and I'm slightly concerned lest IB introduce some new dialog that also happens to contain that word in the title. 

Are you aware of any other places where the brand name appears? It seems rather odd to me that it should be in the config dialog's title but not the main gateway window.

So how urgent is it to fix this? If you can remove the branding until I can get the next version of IBController out, that would be easiest - that might be a while though because there are other things that also need sorting (and it's 'the holiday period'). 

But if it's urgent, I'll produce an interim version for you to test (we may find that you'll come across other similar problems once it gets past the current holdup).

**Comment by rlktradewright** [comment]
Ok, try the version at this link (I thought it best to just do it now, so we can at least see whether that gets you going or just throws up more of the same):

https://1drv.ms/u/s!AlqfLEOWDJ9Zhpc6B4gTjiv5wjKN4w

**Comment by shakti-vyjayanthi** [comment]
Hi, 

I tried with the updated version that you provided, but it is still not going beyond that page. Can you tell me which file(s) were changed so that I can analyse if I am doing something wrong?

**Comment by rlktradewright** [comment]
The only source file changed was

src\IBController\GlobalConfigurationDialogHandler.java

In that file, line 53 was changed from

return (SwingUtils.titleContains(window, "Trader Workstation Configuration"));

to

return (SwingUtils.titleContains(window, "Configuration"));

In the IBController log file you should see lines similar to this:

12:25:45:170 IBController: detected dialog entitled: Kristal Configuration; event=Activated
12:25:45:233 IBController: detected dialog entitled: Kristal Configuration; event=Opened
12:25:45:248 IBController: Performing port configuration
12:25:45:530 IBController: TWS API socket port was set to 4002
12:25:45:545 IBController: TWS API socket port now set to 7498
12:25:45:545 IBController: Click button: OK

**Comment by shakti-vyjayanthi** [comment]
Hi, 

It started working! Thank you for the quick fix! :)
