### ISSUE TITLE
Error creating minimal file C:Jts\jts.ini

### ISSUE THREAD

**Issue by utahman** [ib-controller/ib-controller#132]
IBController is trying "Creating minimal C:Jts\jts.ini" and failing because it should use "C:\Jts\jts.ini".
Where does it get "C:Jts"? All environment variables are set correctly.
Latest Windows 10
TWS version 963

**Comment by rlktradewright** [comment]
This probably means that you've set 

`IbDir=C:\Jts`

in IBController.ini.

Please read the comments in IBController.ini relating to this setting. Or, don't bother, I'll just quote it for you:

    # Note that, for Windows users, you MUST use double separator 
    # characters to separate the elements of the folder path: for
    # example, IbDir=C:\\IBLiveSettings is valid, but
    # IbDir=C:\IBLiveSettings is NOT valid and will give unexpected 
    # results. Linux and OS X users need not use double separators,
    # but they are acceptable.
    #
    # The default is the current working directory when IBController is
    # started.
    
    IbDir=
    

Note also that since `C:\Jts` IS the current working directory when IBController is started, you don't need to set this at all.

**Comment by utahman** [comment]
I read it but set in the wrong file.
It's a bit confusing that there are two settings. One in .ini and one in .bat file
IbDir=C:\\Jts
set TWS_PATH=C:\Jts
Thank you!
