### ISSUE TITLE
cannnot start from java

### ISSUE THREAD

**Issue by arbitrage-technology** [ib-controller/ib-controller#137]
using manually via the shell,  IBControllerGatewayStart.sh works as expected 
but the code:

File path = new File("/home/user/IBController/IBControllerGatewayStart.sh")
path.setExecutable(true);

ProcessBuilder pb = new ProcessBuilder("/bin/sh", path.getAbsolutePath());
Process p = pb.start();
p.waitFor()

doesnt work EXCEPT if i put breakpoint after start().

it runs ok in debug mode but not as a stand alone.

any idea to launch scripts from java program ?

**Comment by rlktradewright** [comment]
Well since you haven't bothered to give us any information - you don't even explain what you mean when you say it doesn't work - I don't know what sort of help you expect. You also don't say what you expect to happen.

Since it does 'work' when you put a breakpoint on the waitFor() call, the start method on the ProcessBuilder obviously does what you expect, so this doesn't really even seem to be an IBController issue.

However perhaps it would help if you realise that the IBController process isn't the same process as the one you're waiting on. You are waiting on the shell process, but the script runs IBController in a separate background process and then exits.

**Comment by shevkoplyas** [comment]
i guess it happens due to the fact that "IBControllerGatewayStart.sh"
script is not blocking (it starts something else in a background and
exits). Look at the last line from that script:

(quote)
"${IBC_PATH}/Scripts/DisplayBannerAndLaunch.sh" &
(end of quote)

so your "p.waitFor()" does not actually wait anythig. You'd either fall
"asleep" in your code or remove "&" from Richard's script (which I would
not recommend (don't mess with Richard's scripts:))

**Comment by arbitrage-technology** [comment]
thanks to  shevkoplyas.

taking out & character in "${IBC_PATH}/Scripts/DisplayBannerAndLaunch.sh" & 
makes IBControllerGatewayStart.sh "launchable" from java program trough ProcessBuilder() class.

thx for your fast reply and your help.

**Comment by shevkoplyas** [comment]
happy to help..  just don't tell Richard I suggested to modify the script ;
)
