### ISSUE TITLE
IBController: Rewriting existing c:\Jts\jts.ini... why?

### ISSUE THREAD

**Issue by spa2000** [ib-controller/ib-controller#146]
Hello

I see this in the logs.. IB Controller was working fine daily and then suddenly this. Restarting IB Controller fixed it. This was last week and I didn't see it again.. what caused this and how can I be sure it won't happen again?

Thanks
Phil
_______________

15:36:57:236 IBController: using default settings provider: ini file is C:\_System\IBControllerMASTER\IBControllerMASTER.ini
15:36:57:236 IBController: using default login manager: getting username and password from args but not found. Will get from settings
15:36:57:236 IBController: using default config dialog manager: constructor parameter isGateway=true
15:36:57:236 IBController: using default trading mode manager: constructor parameter args: tradingMode=live
15:36:57:236 IBController: using default config dialog manager
15:36:57:314 IBController: IBControllerServer is started.
15:36:57:938 IBController: IBControllerServer listening on address: WIN-62SJITBT0US/172.30.1.29 port: 7462
15:36:58:952 IBController: Ensuring c:\Jts\jts.ini contains required minimal lines
15:36:58:952 IBController: Found section: [Logon]
15:36:58:952 IBController: Found section: [Logon]
15:36:58:952 IBController: Missing lines in c:\Jts\jts.ini
15:36:58:952 IBController: Rewriting existing c:\Jts\jts.ini
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
15:36:58:952 IBController: Problem writing to c:\Jts\jts.ini: c:\Jts\jts.ini (Access is denied)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IBGateway finished

**Comment by rlktradewright** [comment]
jts.ini is a file that TWS uses to govern certain aspects of its operation. Curiously, there are a couple of lines that, if not present in the file, result in TWS displaying a login screen with an incorrect format, and consequently IBController is unable to successfully initiate the login process.

So to avoid possible problems where, for example, the jts.ini file is somehow deleted (it shouldn’t ever happen but people do silly things sometimes), IBController checks that jts.ini contains these problem lines and inserts them if it doesn’t.

So, what caused this is that for some reason your jts.ini file was changed in such a way that it no longer contained these lines. I can’t tell why this happened, but it certainly did, because the file certainly existed and it certainly didn’t contain those lines. But why access should be denied is equally mysterious. The TWS installation process doesn’t put any unusual permissions on any of the files it installs. So something else must have changed jts.ini and given it restrictive file permissions. 

Then there’s the question why it didn’t happen again, and the answer may simply be that you ran TWS manually: when you do this, TWS itself rewrites jts.ini to contain the correct information, so IBController won’t subsequently complain (however it doesn’t do this soon enough to avoid IBController’s difficulties with an incorrect jts.ini, which is why IBController has to do the rewriting).

How can you be sure it won’t happen again? Just make sure nothing that happens on your machine messes with jts.ini, and in particular make sure that whatever user you run IBController under always has write access to the TWS and IBController installation directories.

**Comment by spa2000** [comment]
Thanks for your reply.. IBController failed again today and somehow TWS got messed up (TWS would not launch at all with manual launch). I had to reinstall TWS to fix this.

Could my problems be something to do with fact I am launching mutiple TWS gateways at once using IB controller. I have 3 accounts with IB and I need gateway for each...launched by 3 IBControllers instances. This has been working fine until recently.

Today i saw this log for first IBController launched gateay

15:36:58:952 IBController: using default settings provider: ini file is C:\_System\IBControllerMASTER\IBControllerMASTER.ini
15:36:58:952 IBController: using default login manager: getting username and password from args but not found. Will get from settings
15:36:58:952 IBController: using default config dialog manager: constructor parameter isGateway=true
15:36:58:952 IBController: using default trading mode manager: constructor parameter args: tradingMode=live
15:36:58:952 IBController: using default config dialog manager
15:36:59:311 IBController: IBControllerServer is started.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
15:37:00:793 IBController: exception:
java.net.BindException: Address already in use: JVM_Bind
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
15:37:00:793 IBController: IBControllerServer failed to create socket
15:37:02:727 IBController: Ensuring c:\Jts\jts.ini contains required minimal lines
15:37:02:727 IBController: Found section: [Logon]
15:37:02:727 IBController: Found section: [Logon]
15:37:02:727 IBController: Missing lines in c:\Jts\jts.ini
15:37:02:727 IBController: Rewriting existing c:\Jts\jts.ini
15:37:02:727 IBController: TWS settings directory is c:\Jts
15:37:34:551 IBController: detected frame entitled: IB Gateway; event=Activated
15:37:34:567 IBController: detected frame entitled: IB Gateway; event=Opened
15:37:34:739 IBController: Click button: Login
15:37:35:684 IBController: detected frame entitled: IB Gateway.  API Account: xxx; event=Activated
15:37:35:731 IBController: detected frame entitled: IB Gateway.  API Account: xxx; event=Opened
15:37:35:731 IBController: Found Gateway main window
15:37:36:199 IBController: detected frame entitled: Authenticating ( trying for another 19 seconds)...; event=Activated
15:37:36:199 IBController: detected frame entitled: Authenticating ( trying for another 19 seconds)...; event=Opened
15:37:37:073 IBController: detected frame entitled: Authenticating ( trying for another 19 seconds)...; event=Activated
15:37:37:088 IBController: detected frame entitled: Authenticating ( trying for another 19 seconds)...; event=Activated
15:37:37:478 IBController: detected frame entitled: IB Gateway; event=Activated
15:37:37:509 IBController: detected dialog entitled: IB Gateway; event=Activated
15:37:37:509 IBController: detected dialog entitled: IB Gateway; event=Opened
15:47:16:519 IBController: detected dialog entitled: IB Gateway; event=Activated
15:47:21:901 IBController: detected frame entitled: IB Gateway; event=Activated
15:47:25:380 IBController: detected frame entitled: IB Gateway; event=Closing
15:47:25:395 IBController: detected frame entitled: IB Gateway; event=Closed

And this for second IBController..

15:36:58:952 IBController: using default settings provider: ini file is C:\_System\IBControllerPENSION\IBControllerPENSION.ini
15:36:58:952 IBController: using default login manager: getting username and password from args but not found. Will get from settings
15:36:58:952 IBController: using default config dialog manager: constructor parameter isGateway=true
15:36:58:952 IBController: using default trading mode manager: constructor parameter args: tradingMode=live
15:36:58:952 IBController: using default config dialog manager
15:36:59:311 IBController: IBControllerServer is started.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
15:37:00:793 IBController: exception:
java.net.BindException: Address already in use: JVM_Bind
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
15:37:00:793 IBController: IBControllerServer failed to create socket
15:37:02:727 IBController: Ensuring c:\Jts\jts.ini contains required minimal lines
15:37:02:727 IBController: Found section: [Logon]
15:37:02:727 IBController: Found section: [Logon]
15:37:02:727 IBController: Missing lines in c:\Jts\jts.ini
15:37:02:727 IBController: Rewriting existing c:\Jts\jts.ini
15:37:02:727 IBController: TWS settings directory is c:\Jts
15:37:34:551 IBController: detected frame entitled: IB Gateway; event=Activated
15:37:34:684 IBController: detected frame entitled: IB Gateway; event=Opened
15:37:34:801 IBController: Click button: Login
15:37:35:606 IBController: detected frame entitled: IB Gateway.  API Account: xxx; event=Activated
15:37:35:606 IBController: detected frame entitled: IB Gateway.  API Account: xxx; event=Opened
15:37:35:606 IBController: Found Gateway main window
15:37:36:105 IBController: detected frame entitled: Authenticating ( trying for another 19 seconds)...; event=Activated
15:37:36:105 IBController: detected frame entitled: Authenticating ( trying for another 19 seconds)...; event=Opened
15:37:37:073 IBController: detected frame entitled: Authenticating ( trying for another 19 seconds)...; event=Activated
15:37:37:073 IBController: detected frame entitled: Authenticating ( trying for another 19 seconds)...; event=Activated
15:37:37:088 IBController: detected frame entitled: Authenticating ( trying for another 19 seconds)...; event=Activated
IBGateway finished

**Comment by rlktradewright** [comment]
The User Guide contains a section on how to set up multiple instances of IBController (it's in the penultimate section of the Guide). If you haven't already read and understood it, can I suggest you do so now.

So you should end up with three different IBController start scripts, and three different IBController.ini files, and the `IbDir` settings in the .ini files should point to three different directories.

What the Guide doesn't mention is that strictly speaking the `IbControllerPort` settings in the .ini files should also be different (eg, 7462, 7463 and 7464). If they're not different you'll get the 'Address already in use' exception message that you can see in your logs, but that won't actually affect correct operation of IBController (unless you want to use IBController's command server, which hardly anyone does).

More importantly, the Guide should also say that the `set LOG_PATH=` line in the start script must also be different for the three cases, otherwise each IBController instance will try to use the same log file.

One of these days I'll get round to updating the User Guide to clarify these points...

**Comment by rlktradewright** [comment]
@spa2000 
Are you still having problems with this? If not, please close the issue.

**Comment by spa2000** [comment]
Hello

Many thanks for your advice on this and sorry for not getting back to you.  My solution (which seem to be holding) is to simply not launch multiple Ib controller simultansously.
