### ISSUE TITLE
Permission denied/Operation not permitted

### ISSUE THREAD

**Issue by nikolom** [ib-controller/ib-controller#149]
I installed the Controller and run these commands in Terminal with these denial results:

MacBook-Pro:IBController nikol$ ./IBControllerStart-OSX.sh
-bash: ./IBControllerStart-OSX.sh: Permission denied

MacBook-Pro:IBController nikol$ chmod -R u+x *.sh
chmod: Unable to change file mode on IBControllerStart-OSX.sh: Operation not permitted

Please, can you help? How can I get the permission?

Thank You.

**Comment by rlktradewright** [comment]
I was going to suggest that you use this command to set the permissions:

 

sudo chmod u+x *.sh */*.sh

 

This will ensure that you also have execute permission to the .sh files in the Scripts subdirectory.

 

But then I realised that it’s not letting you chmod the files at all. 

 

I don’t have access to a Mac so I can’t make any useful suggestion other than to make sure your user owns the files.

 

Richard

**Comment by shevkoplyas** [comment]
I guess if you can not chmod file on your harddrive then the file is owned
by some other user. May be you installed it as "root" and now trying to
chmod as user "nikol" ?

try to:
1) change directory to your IBController:
cd IBController

2) list all the files there with ownership and permissions:
ls -l

3) check what user are you right now:
whoami

and either paste what you saw here or proceed accordingly (with your
knowledge)

cheers,
Dmitry

**Comment by nikolom** [comment]
Dmitry,
1.I start with IBController directory:
MacBook-Pro:IBController nikol$ ls
IBController.ini        IBControllerStart.sh
IBController.jar        LICENSE.txt
IBControllerEncrypt.bat     README.txt
IBControllerGatewayStart-OSX.sh Scripts
IBControllerGatewayStart.bat    Start TWS Live (daily).xml
IBControllerGatewayStart.sh userguide.pdf
IBControllerStart-OSX.sh    version
IBControllerStart.bat
MacBook-Pro:IBController nikol$

2. MacBook-Pro:IBController nikol$ -l
-bash: -l: command not found
 
3. MacBook-Pro:IBController nikol$ whoami
nikol

Thank You.

**Comment by shevkoplyas** [comment]
I see your username is "nikol", but your step 1) and 2)  should be actually
one command "ls -l" and it should produce long listing format of all the
files (including ownership and permissions), like this:

[image: Inline image 1]

**Comment by nikolom** [comment]
Richard and Dmitry, thank you. I am working with my university laptop for which I thought I had admin privileges but apparently not so since user name "staff" appears here. I will ask them to override it.

MacBook-Pro:IBController nikol$ ls -l
total 752
-rw-r--r--@ 1 root  staff   18134 May 12  2016 IBController.ini
-rw-r--r--@ 1 root  staff   71164 Jun  2  2016 IBController.jar
-rw-r--r--@ 1 root  staff     252 Jul  3  2014 IBControllerEncrypt.bat
-rw-r--r--@ 1 root  staff    5521 Jun  1  2016 IBControllerGatewayStart-OSX.sh
-rw-r--r--@ 1 root  staff    6202 May  2  2016 IBControllerGatewayStart.bat
-rw-r--r--@ 1 root  staff    5428 May 16  2016 IBControllerGatewayStart.sh
-rw-r--r--@ 1 root  staff    5008 Jun  1  2016 IBControllerStart-OSX.sh
-rw-r--r--@ 1 root  staff    5570 May  2  2016 IBControllerStart.bat
-rw-r--r--@ 1 root  staff    4933 May 16  2016 IBControllerStart.sh
-rw-r--r--@ 1 root  staff   33096 Jul  3  2014 LICENSE.txt
-rw-r--r--@ 1 root  staff     144 Jul  3  2014 README.txt
drwxr-xr-x@ 8 root  staff     272 Jun  2  2016 Scripts
-rw-r--r--@ 1 root  staff    4458 Aug  4  2014 Start TWS Live (daily).xml
-rw-r--r--@ 1 root  staff  181402 May 14  2016 userguide.pdf
-rw-r--r--@ 1 root  staff       5 Jun  2  2016 version

**Comment by nikolom** [comment]
This is how I fixed the permissions:  In the IBController folder I typed
sudo chown -R nikol *
I added
chmod +x

Now it runs (./IBControllerStart-OSX.sh) but in the log file it states: TWS version 965 is not installed: can't find /Users/nikol/Applications/IB Gateway 965/jars
In the directory Users/nikol/Applications/ I have TWS 965.*. Why is it asking for Gateway? I use TWS and not Gateway.

Thank You.

**Comment by rlktradewright** [comment]
As far as IBController is concerned, the TWS and Gateway installs contain identical code. Therefore it doesn’t matter whether you installed TWS only, Gateway only or both TWS and Gateway: the IBController scripts first check for the presence of the TWS install and use that if it finds it; if it doesn’t find TWS, it will look for the Gateway install and use that if it finds it. The error message you got merely indicates that it didn’t find either, but I admit that it’s misleading and will change it to be more informative.

But the point is, did you read the rest of the error message? It tells you exactly what is wrong. This happens over and over again, where new users don’t follow the very simple installation instructions and try to run IBController with the self-updating version of TWS rather than the offline version. Read my lips:

**IBController does not work with the auto-updating TWS !!!!!**

So go back to IB's website, download the offline version of TWS, install it and try again.

**Comment by nikolom** [comment]
Richard, I really do not like the tone of your message. I did read the whole error message. Second, I am not a programmer or IT guy and I was assuming I did have the offline version. I do not not even know another version exists. This "read my lips" message is insulting. If you do not have the patience to answer questions, some of which may be repetitive for you, just don't answer at all.

**Comment by rlktradewright** [comment]
I'm sorry that you're insulted. It might help if you try to understand my frustration. I have spent literally thousands of hours trying hard to make IBController a program that is as easy to use as possible, particularly since I know very well that many of its users are not programmers or IT guys. For that significant chunk of my life, I have not received a single penny in payment (except £100 GBP in return for a special modification I made for a Russian firm, and a bottle of whisky from a grateful user).

So I like to feel my time, and that of others who contribute to resolving issues here, is well spent. When I feel that someone is wasting my time because they haven't taken the trouble to read the documentation they were provided with, that irritates me.

I take pride in my work, and my reward is the knowledge that I'm providing a useful little product for TWS/Gateway users, and also the fact that from every real problem that users face I learn something worthwhile.

In particular the User Guide is very explicit in telling you what to do to make IBController work. All you have to do is follow the simple instructions there. The User Guide says, in bold type in at least two places, that you must use the offline version of TWS, so please don't try to tell me that you're insulted by my insinuation that you haven't followed the instructions in the same breath as saying that you've never heard of the offline version. I find THAT insulting!

Now, I said above that I always learn something when someone has a real problem with IBController. In this case, the only real problem that you faced was the permissions issue. What I've learned here is that the User Guide is not explicit enough about how to set the permissions, and that was largely because most Linux users are fairly familiar with this subject, but that is clearly no longer a valid assumption. So I will make an effort to update the User Guide to provide better guidance when setting up IBController on Linux or macOS. 

Finally, on the question of whether I 'have the patience to answer questions', I think if you glance through my contributions here on Github, in the IBController User Group at [https://groups.io/g/ibcontroller](https://groups.io/g/ibcontroller), and (before the IBController User Group was set up) in the TWS API Users Group at [https://groups.io/g/twsapi](https://groups.io/g/twsapi), you might find an answer!

**Comment by nikolom** [comment]
I read your user guide several times. So your immediate assumption that it was no read is plain wrong.
I am a teacher and one thing that is expected of me is to show infinite patience in repeating the same info over again. Just because you made contributions does not mean you have the right to behave in a condescending manner. Take that somewhere else. You think you are more than you are.

**Comment by rlktradewright** [comment]
Well, I can only admire your penetrating insights into my character...

Now, if you don't mind, let's get back to getting you up and running.

Contrary to what I said earlier, on reflection I don't think it's necessary to add more to the User Guide regarding how to set the permissions. What I'll do is replace the relevant section with the following:

```
#### On Unix: 

- unpack the ZIP file using a command similar to this:

sudo unzip ~/Downloads/IBController-3.3.0.zip -d \
/opt/IBController

- now make sure all the script files are executable:

cd /opt/IBController
sudo chmod o+x *.sh */*.sh
```

Note that there is no need to change the ownership of the files. The chmod command will give execute access to all users.

What I suggest you do is wipe out your existing /opt/IBController and ~/IBController directories and start again, using the offline version of TWS. Use the command above instead of the one in the current User Guide. You should find that It Just Works.

**Comment by herrold** [comment]
@nikolom But this is not a school, and @rlktradewright is doing this as a wholly volunteer effort (my comment has been 'sitting in compose' unsent, for a couple hours, and I see he has also chimed in). As this GitHub locale is the primary archive for this software, there is not a 'better' place to 'take' whatever effort is offered.  

I rather doubt that any teacher deriving some compensation, financial or intellectual from teaching, would display _infinite_ patient repeating what is covered in the documentation over and over to a pupil who does not read and understand.  Perhaps the pupil owns the obligation to participate in his edification by reading, and when unclear, and to propose well formed questions to narrow down where his understanding fails from the documentation.

**Comment by nikolom** [comment]
Thank you Richard.
