### ISSUE TITLE
Request: Telnet Command that confirms that TWS/Gateway has started

### ISSUE THREAD

**Issue by mission2010** [ib-controller/ib-controller#15]
I am automating my trading process and came across IBController. It is a very helpful tool!

After I execute the BATCH file I would like to know whether the TWS/Gateway has loaded/started or not.

It would be great to have a Telnet command that gives you the information whether the TWS/Gateway has started. 

**Example:**
Telnet command: `ISTWSUP`
Reply: `TRUE/FALSE, OK/NOK, YES/NO`

Would it be possible to implement something like this? Is there maybe another way to determine the current execution state?

Many thanks!

**Comment by rlktradewright** [comment]
When IBController starts, it loads TWS/Gateway almost immediately (within milliseconds). Once it has done that, as far as IBController is concerned TWS/Gateway is ‘up’. It knows nothing about the state of TWS/Gateway: for example, it has no idea when or whether TWS/Gateway has started to listen on the API socket. This is because the only purpose for IBController is to react to certain user interface events initiated by TWS/Gateway, and to respond to commands issued to its own command server. It has no other way of monitoring TWS/Gateway.

 

So it’s not clear to me what information you would expect to gain from such a command. What would a ‘true’ response actually be expected to indicate?

 

If you want to know when it’s ok to try connecting to the API, the best thing is for your app simply to try connecting to the API socket: if the connection attempt fails, just try again after a few seconds. IBController has no information that could help you with this.

 

It may be that you have an incorrect mental model of the relationship between IBController and TWS/Gateway. IBController is NOT a separate process that can observe and potentially monitor TWS/Gateway. IBController loads TWS/Gateway into IBController’s own address space, so IBController and TWS/Gateway are both in the SAME process. So if, for example, TWS crashes, then IBController disappears with it: IBController cannot somehow catch this event and subsequently report it in response to a query.

 

Now it would be possible to develop a separate application that would run in its own process and monitor one or more TWS/Gateway processes, but any such monitoring would have to be done via the API socket and by using operating system-specific process management features. It would not be able to do what IBController does in a cross-platform way. Such a process is totally different from IBController’s purpose, and is way outside the scope of the IBController project.

**Comment by mission2010** [comment]
Hi!

Many thanks for your answer!

> If you want to know when it’s ok to try connecting to the API,...

This is exactly what I was looking for. I will rework my internal program flow and use the TWS API to find out whether the TWS is ready to connect or not.

**Comment by benalexau** [comment]
Closing this ticket as it's outside the scope of IBController as per earlier discussion.
