### ISSUE TITLE
Always says missing lines in the jts.ini, recreates

### ISSUE THREAD

**Issue by mwahal** [ib-controller/ib-controller#150]
Running IBController-3.3.0-beta.3 on Mac OSX 15.6.0 Darwin Kernel Version 15.6.0
 
It always says missing lines and rewrites. Even if I delete the jts.ini file, it creates the jts.ini file once, and then second iteration, it says missing line and rewriting.

-rw-r--r--  1 xxx  staff  291 Jun 22 16:02 jts.ini

16:02:20:923 IBController: Found section: [Logon]
16:02:20:923 IBController: Found section: [Logon]
16:02:20:923 IBController: Found setting: s3store=true
16:02:20:923 IBController: Found section: [IBGateway]
16:02:20:923 IBController: Missing lines in xxx/jts.ini
16:02:20:923 IBController: Rewriting existing xxx/jts.ini

=== now I remove the file ====
rm jts.ini
==== starting IBController ====
16:08:47:183 IBController: IBControllerServer listening on address: 0.0.0.0 port: 13003
16:08:47:190 IBController: Creating minimal xxx/jts.ini
16:08:47:195 IBController: TWS settings directory is xxx/MWRA1
16:08:49:673 IBController: detected frame entitled: Login; event=Opened
...
16:09:36:967 IBController: detected dialog entitled: Uploading settings to server; event=Closed
16:09:36:967 IBController: detected dialog entitled: Uploading settings to server; event=Closed
16:09:37:557 IBController: detected frame entitled: Loading...; event=Closed
IBController finished

==== Now I close the TWS App and start again ====

16:09:57:809 IBController: Ensuring xxx/jts.ini contains required minimal lines
16:09:57:809 IBController: Found section: [Logon]
16:09:57:809 IBController: Found section: [Logon]
16:09:57:809 IBController: Found setting: s3store=true
16:09:57:809 IBController: Found section: [IBGateway]
16:09:57:809 IBController: Missing lines in xxx/jts.ini
16:09:57:810 IBController: Rewriting existing xxx/jts.ini

========

Please let me know if you any debugging info etc to be collected.

Thanks
Mudit

**Comment by mwahal** [comment]
I think I found the problem -- look at the existingFileOk, its checking for "&", not "&&"

 private static boolean existingFileOk() {
        return (findSettingInSection(LogonSectionHeader, S3storeFalseSetting) || 
                findSettingInSection(LogonSectionHeader, S3storeTrueSetting)) **&**
                findSettingInSection(IBGatewaySectionHeader, ApiOnlyTrueSetting);
    }

**Comment by mwahal** [comment]
After that change, now it doesn't complain about the rewriting ini file.

20:00:08:749 IBController: Found section: [Logon]
20:00:08:749 IBController: Found setting: s3store=true
20:00:08:749 IBController: Found section: [IBGateway]
20:00:08:749 IBController: Found setting: ApiOnly=true
20:00:08:749 IBController: Confirmed xxx/jts.ini contains required minimal lines
20:00:08:749 IBController: TWS settings directory is xxx
20:00:11:819 IBController: detected frame entitled: Login; event=Opened

**Comment by rlktradewright** [comment]
Actually that & is correct, but there are other bugs in the Jts re-writing code in the IBController-3.3.0-beta.3 release. These were fixed in [this commit](https://github.com/ib-controller/ib-controller/commit/643f442d4d7a74b6e709083279bfbd7f2c37422a), but I haven't done a formal release since then.

So if you download the latest version of IBController.jar from [here](https://github.com/ib-controller/ib-controller/tree/master/resources), you should have no further problems.

**Comment by mwahal** [comment]
I downloaded the master zip file, made my change to && and it worked. But it may have your changes already in there, so the & to && probably didnt change anything. Normally, you will use "&" to check the bitfield positions in a flag etc. But in this case, you are call two different functions to check whether the section is there or not, which is a logical/boolean return and not a flag set/clear. That's why I thought, it needed a "&&".

Thanks
Mudit

**Comment by rlktradewright** [comment]
You don't need to change anything! I told you what to do: download the latest version of IBController.jar, which contains the correct version of the Jts.ini re-writing code. The IBController-3.3.0-beta.3.zip file on the Releases page does NOT contain the latest version and has bugs in that code, as I said before.

The reason that & is correct and && is not, is that when you use & or | in a Boolean expression, both sides of the expression are evaluated, whereas if you use && or || then the right-hand side is not evaluated if the left-hand side already determines the logical outcome (ie short-circuiting). In my code, I want the logging that findSettingInSection(IBGatewaySectionHeader, ApiOnlyTrueSetting) does to occur regardless of whether the previous calls to findSettingInSection() succeeded or failed. On the other hand, if the first call to findSettingInSection() succeeded, there's no point in making the second call because that has to be false.

It has nothing whatever to do with setting or clearing flags.

**Comment by mwahal** [comment]
I removed my changes and recompiled the jar file. The master already has your fix. Thanks.
