### ISSUE TITLE
Read only mode in Gateway 966.1c

### ISSUE THREAD

**Issue by chrism2671** [ib-controller/ib-controller#156]
I've upgraded my docker script to run this with gateway 966.1c, but it seems like its stuck in read-only API mode. Is it out-of-the-box compatible with 966.1c?

Thanks,
Chris.

**Comment by ChromoX** [comment]
I have the same exact problem with version 967.1b.

**Comment by rlktradewright** [comment]
This is a 'problem' with every version of TWS/Gateway (since 956 or something like that).

It is absolutely nothing whatever to do with IBController. IBController never has been a configuration tool for TWS/Gateway. You have to configure your instance in whatever way suits your purposes, outside of IBController.

If you've had a working setup before, you must have done this configuration at some point (unless you're moving up from an older version like 952 or earlier). You only have to do it once, so you've probably forgotten about it.

See also Issue #157.

**Comment by rlktradewright** [comment]
Closing this due to lack of further comment.
