### ISSUE TITLE
programmatically set API XML settings

### ISSUE THREAD

**Issue by pgeez** [ib-controller/ib-controller#157]
I'm on 963.3h

Is there a way to programmatically set any/all of the configuration options found under the `APISettings` tag in `ibg.xml`?

Specifically, I'd like to set `autoOpenOrdDonwload=false` which has the effect of disabling ("un-checking") "Download open orders on connect" in the GUI.

Thanks!

**Comment by rlktradewright** [comment]
No, there isn't.

It's not IBController's function to configure TWS/Gateway. Just configure it manually the way you want it. If it's difficult to do this on the machine it will be running on (eg headless or Docker image) just configure it on a local computer and copy the entire Jts directory tree to the target.

**Comment by pgeez** [comment]
@rlktradewright Ok, thanks for the info.

However, the trick with copying the entire directory over is that the Gateway "encrypts" the username so it's impossible to know the exact JTS target directory at build time.

**Comment by rlktradewright** [comment]
I presume you're referring to the directories with names like djkknie? These aren't encrypted usernames, they're actually associated with the account name.

For live and paper accounts, a given user logging on to a particular account will always use the same directory, so this trick should work in that case.

If you're trying to use the demo account, you're out of luck. The trouble is that when you logon to the demo account, you are actually assigned one of a number of accounts at random, and a corresponding settings folder is generated. However these accounts are initialised each time with default settings that aren't what you want, so even if you could predict which directory was going to be used, you couldn't do it this way.

**Comment by rlktradewright** [comment]
Since there has been no further comment on this, I'll close it now.

**Comment by dsimba** [comment]
I have been following some recurrenr thread. This is a good feature to have. Clearly not usefull to you Richard, but to others it is!

**Comment by rlktradewright** [comment]
@dsimba 

Please don't resurrect dead threads without good reason. This one has been closed for over a year. 

This is NOT a good feature to have in IBController. It has nothing whatsoever to do with IBController's purpose.

If you want to mess with TWS's settings file, there's nothing to stop you editing it. If you want to do it programmatically, you can write a program to do it and then run the program before you run IBController. If you can't program, find someone who can. But don't hope that I'll do it, because I absolutely promise I'm not going to.

In any case, you're barking up entirely the wrong tree: no-one is maintaining IBController now, as any of the recent issues will tell you. You should now be using IBC: https://github.com/IbcAlpha/IBC
