### ISSUE TITLE
Ibcontroller 3.4.2 - failing running

### ISSUE THREAD

**Issue by Nabladelta76** [ib-controller/ib-controller#158]
Hi everyone,
I downloaded the last version of IbController, but it fails running with this log message (I translate it from Italian, so I am sorry if the terminology will not be accurate):
"It is impossible to find or load the principal class: ibcontroller.IBController"
I understand the file is missing, is it correct?
I point that I was never able to complete the first run of IbController, to verify everything was alright, before personalising the settings to login in TWS.
Has anyone encountered this problem? May it be an issue due to my java? 
Thank you in advance for any feedback.
Regards,
Daniela

**Comment by rlktradewright** [comment]
Why don't you post the IBController log file so that we have some information to go on? That's what it's for!

Just attach it to your reply (ie don't include the contents of the log file in your post).

Also, every run of IBController on one day uses the same log file (appending to it each time), so either edit it to remove all but one run, or delete the log file, run IBController again, and then attach the log file.

**Comment by Nabladelta76** [comment]
[ibc-_TWS-963_TUESDAY.txt](https://github.com/ib-controller/ib-controller/files/1227652/ibc-_TWS-963_TUESDAY.txt)
Here is the last log file.

**Comment by rlktradewright** [comment]
Thanks for the log file.

This seems to indicate that you are missing two vital files from C:\IBController. These are:

* IBController.jar
* version

Perhaps you tried to remove unnecessary files from C:\IBController, but in doing so you got rid of the very file that actually IS IBController, ie IBController.jar? So you'll probably need to extract them from the zip file again.

By the way, you need to make sure that TWS is running in English, otherwise IBController won't recognise the dialogs it displays and won't work. I think it should be OK if Windows is running in an Italian locale, provided TWS is English.

**Comment by Nabladelta76** [comment]
Thank you for your answer. I think it is all right now: both files you mentioned were in C:\IBController, but they where in different directories. I corrected the setting about the language for TWS and the first run is now ok. I'll proceed with the custom configuration. The issue is closed to me. Thank you.
