### ISSUE TITLE
Setting up timezone on ib-controller

### ISSUE THREAD

**Issue by HackerzWorkshop** [ib-controller/ib-controller#166]
Hi,
I run windows 10 machine , my local time is GMT+2 but I want log in to TWS with America\New_York timezone.
When I log-in manually I can set TWS timezone to whatever I want , but I can't find this option in the IBControllerStart.bat configuration file.

Thanks,
Sasha

**Comment by rlktradewright** [comment]
There is currently no option for this. You are the first person that has ever expressed an interest in being able to do it.

It may be possible to provide it, but first I need to do some investigation into what exactly the timezone dropdown on the login screen actually is. Some of what appear to be dropdowns are actually proprietary IB components that do not offer the normal Swing interfaces, and with these it's not possible for IBController to set the value.

I'll try to find time to check this out soon, but if I don't respond within a couple of days, please feel free to nudge me.

**Comment by HackerzWorkshop** [comment]
Thank for your help ! Hope you will have some spare tine to look at it

**Comment by rlktradewright** [comment]
I've had a quick look and at this stage it's not encouraging. I have a tool that analyses and logs the structure of each dialog that IBController encounters. (The `LogComponents` setting in IBController.ini governs the output of this data if you want to see for yourself - it's best to temporarily remove your password from jts.ini so you can see what happens when you click the 'More options' link.)

The problem is that this output does not seem to include a JButton corresponding to the 'Timezone...' button, so IBController will not be able to click it to display the timezone selection dialog.

Oh dear, I've just realised I'm being very stupid here. You don't need to do this via IBController at all. Just start TWS (manually will do nicely), set the timezone you want, and TWS will remember your choice for the next time you login.

Job done...
