### ISSUE TITLE
Task Scheduler not closing TWS

### ISSUE THREAD

**Issue by bobsyd** [ib-controller/ib-controller#169]
No responses in the User Group yet, so I am submitting this updated version of the issue here.

Am running IB Controller 3.4.0 with TWS 963.3k, 24 October 2017, using a Paper Trading account on a cloud VPS running Windows Server 2012 R2.  Have set up a task in Task Scheduler to start TWS, which it does.  In Task Settings, I have set Stop the task if it runs longer than: 15 minutes.  (Once orders are entered, which they are via the API well within the 15 minute window, I want the capability to manually open TWS to check on orders/positions.) However, the task keeps running beyond 15 minutes and manually selecting End doesn't stop the task either.
  
When I log in to TWS it asks if I want to stop an existing instance of TWS. I select yes and TWS starts to open, but then no positions or orders are shown because of a message saying TWS is still connected to an API. 

The exact message in TWS is "The API server failed to start since the specified port 7496 is already in use by another application such as another running instance of Trader Workstation.  Please either close the conflicting application and restart Trader Workstation, or change the API socket port on the API>Settings page."

The program I use to send orders to TWS, Trading Blox, which has a built in connection to the IB API, has been closed by this point, so the only other application is another instance of TWS.  The once per day auto logoff should ultimately work, but obviously not keen to wait until then, especially on an ongoing basis.
 
Normal manual shutdown of TWS from within TWS and then restarting doesn't cause this issue.  I note that there is a IBControllerStop batch file, but it uses telnet and I have read that telnet is old technology and not secure.  I am using /INLINE as the argument in Actions and C:\IBController\ in Start in(optional): .  

Suggestions please? My technical knowledge/ability is limited, so please keep that in mind in terms of suggested actions. 

Thanks very much,
 
Bob

**Comment by rlktradewright** [comment]
[I don't see any post from you in the User Group. When did you post it? Was it your first post? Can you tell me the message number?]

Well, I just tried a scheduled task on my Windows Server 20012 R2 and set it to stop after 3 minutes and it worked fine. I think the trick is to use the setting in the trigger definition, rather than in the Settings tab, to define the length of time to run.

It also stopped immediately if I manually ended it from the Task Scheduler manager, so I don't know why it didn't when you tried it. (If you were using Windows 10 or Windows Server 2016, it would be a different matter, but I don't want to have to explain this now if it's not necessary.)

Having said that, is there any reason why you can't just configure TWS's autologoff time to shut it down at the appropriate time?

The IBControlerStop.bat file works well from Task Scheduler. I don't see any reason at all why using telnet internally within your server should be insecure, as long as the firewall doesn't allow telnet connections from outside (which it won't unless you explicitly configure it to). The fact that it's 'old technology' (so is everything else about TCP/IP) is irrelevant.

**Comment by bobgit3** [comment]
Thanks Richard.  I will go with setting the auto-logoff within TWS.  It seems simplest solution.

Sent messages 38918 and 38919 in user group yesterday.  They were first posts.

Thanks again,

Bob
________________________________

**Comment by rlktradewright** [comment]
Ah, I see your messages. Actually you posted them to the TWSAPI group rather than the IBController Group (which is at https://groups.io/g/ibcontroller). Somehow I forgot to check the TWSAPI group for messages, but I'll excuse myself on the grounds that I've been indisposed for the past couple of days...
