### ISSUE TITLE
Script fails with xterm font error

### ISSUE THREAD

**Issue by flogor** [ib-controller/ib-controller#171]
I am running Ubuntu Mate 17.10. Running the IBController shell script fails with the following error message:

`xterm: cannot load font '-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1'`

Is there an additional (hidden) requirement? IB TWS latest and a JRE are installed.

**Comment by rlktradewright** [comment]
The IBController scripts don’t make any special demands of xterm. It sounds like your default xterm configuration is somehow broken,

 

What happens if you just run the xterm command from a terminal session?

 

Alternatively (or if you’re running headless perhaps?) use the -inline switch, eg:

 

./IBControllerGatewayStart.sh -inline

 

which doesn’t use xterm.

**Comment by flogor** [comment]
First, you are right, the xterm error is related to a remote session (x2go). It is actually a warning only (and not a "fatal" error as I thought in the beginning).

Second, the actual issue was that after unpacking the IBController zip file several script files did not have the execute flag set. After fixing this, IBController works perfect.

Thanks for you help! Sorry for the late response and the noise!
