### ISSUE TITLE
How to auto shut down TWS Gateway

### ISSUE THREAD

**Issue by midasSSS** [ib-controller/ib-controller#173]
I run few instances of Gateway at the same time. I know that there is IBControllerStop.bat, but it will only shut down one instance. 

What should I do to be able to shut down Gateways?

Thanks in advance!

**Comment by rlktradewright** [comment]
The easiest thing to do is to create several different IBControllerStop.bat files, one for each IBController instance, eg 

IBControllerStopLive.bat 
IBControllerStopPaper.bat 
IBControllerStopDemo.bat 

Then use different port numbers for the different instances (set these using the IbControllerPort setting in IBController.ini).

**Comment by midasSSS** [comment]
You're right. I have also thought about this. However when I try to change port in .ini file my gateway is not launching

**Comment by rlktradewright** [comment]
What happens? Is there an error message in the logfile.

I can't help you unless you tell me what your experience is.

By the way, this is probably obvious but you will, or course, need a different .ini file for each instance.

**Comment by midasSSS** [comment]
Ok, I think the problem is solved now. Finally, I was able to change port number for different instances.

**Comment by midasSSS** [comment]
However, another problem has arise. I have changed the port in .ini file and I'm able to launch a Gateway. Now, the STOP bat does not work and Gateway is still running...

**Comment by rlktradewright** [comment]
I can't possibly suggest what you're doing wrong unless you tell me what you are doing.

So please explain exactly what you have done, and what happens when you do it.

Once again, I'll remind you about the IBController log file, which may well contain useful information.

**Comment by midasSSS** [comment]
1. In .ini file a have set up the port number 7465 (instead of 7462) and I'm able to launch a Gateway.
2. In IBControllerStop I have set up the same port.
3. So, now, when I launch  IBControllerStop.bat my running instance is not affected and everything continues to work. I can guess that there is an error in this file.

PS. If you need any particular information from the logs I can give it to you

**Comment by rlktradewright** [comment]
Please attach the IBController log file to your reply, the whole of it.

**Comment by midasSSS** [comment]
@rlktradewright 
[ibc-3.4.0_TWS-968_FRIDAY.txt](https://github.com/ib-controller/ib-controller/files/1607057/ibc-3.4.0_TWS-968_FRIDAY.txt)

**Comment by rlktradewright** [comment]
In the logfile you'll see the following:

```
13:43:36:824 IBController: IBControllerServer is started.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
13:43:36:840 IBController: exception:
java.net.BindException: Address already in use: JVM_Bind
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
13:43:36:840 IBController: IBControllerServer failed to create socket
```

As it says, IBController's command server was unable to create the socket on which it listens for commands because something else was already listening on the combination of address and port.

So it looks like you haven't given each instance a different port (since they must presumably all be on the same computer).

**Comment by midasSSS** [comment]
Thats also strange for me. This was during the time when I had only 1 instance running. I don't have an idea why this can be so...

**Comment by midasSSS** [comment]
Am I doing right to change this line in .ini file: IbControllerPort=7465 ?
And in Stop .bat too?

**Comment by rlktradewright** [comment]
Yes that's right.

Perhaps you're starting a new instance of IBController before a previous one has finished shutting down? IBController starts very quickly: in the logfile you'll see that it only takes less than 300 milliseconds to get to the point where it tries to open the socket.

In comparison, TWS takes ages to shut down after IBController has processed the STOP command.

So don't, for example, call STOP.bat followed immediately by START.bat, or you'll almost certainly have this problem.

**Comment by midasSSS** [comment]
Nothing changes. 

Maybe I should change the socket port in Gateway API setting too?

**Comment by rlktradewright** [comment]
No, the socket port in the Gateway API settings is nothing at all to do with the IBController port, and must not be the same.

Something is holding this port open. It's unlikely to be any other program than IBController. So I can only think you are mistaken and there is an IBController instance running that you're overlooking somehow.

You keep talking about the Gateway, and yet the log file you sent is for TWS. This makes me wonder whether you're confused about something.

Why don't you log out of your session to make sure that nothing is running, then log back in and start again. Run one instance of IBController for the Gateway, then run the corresponding STOP.bat, and you'll see that STOP works. Then take it from there to try with more than one instance.

**Comment by midasSSS** [comment]
I have noticed a strange thing. If I do what you say for demo account everything seems to work. However, then I shut down this session and open a real one, with all the same settings, then Stop .bat doesn't work

**Comment by rlktradewright** [comment]
It sounds to me like you've configured the API port and the IBController port to the same value.

Note that there is a setting in the.ini file called something like ForceApiPortNumber: make sure this isn't set the same as the IBController port number. In fact you shouldn't force the API port at all unless you have a real need to: just configure the API port via the TWS/Gateway user interface.

Richard 

[Sent from my lovely Windows 10 phone, now sadly and foolishly obsoleted by Microsoft]

**Comment by midasSSS** [comment]
I have checked it over again, I have different ports.

**Comment by rlktradewright** [comment]
Ok, look, here's the bottom line: IBControllerStop.bat works! There is absolutely no doubt about that. So the only possibility is that you've misconfigured something, and we need to track down what it is.

So please do the following:

1. If you have any scheduled tasks that start IBController, disable them and stop any running tasks. 

2. Shutdown any visible TWS or Gateway instances.

3. Make sure, using Task Manager, that there are no IBController processes left running. Look in the Details tab, and look for java.exe processes. If you have other java processes running that are not IBController, you can tell the difference by ensuring that the 'Command line' column is displayed in the Details tab: then you can see exactly how each process was started. Let me emphasise that it's not enough merely to look at the screen to see if there are Gateway or TWS instances running, because if you're using Task Scheduler you may have inadvertently configured them such that they aren't actually visible in your user session: if you need more information about this, I'll explain it for you, but if you're not using Task Scheduler then it isn't an issue.

4. If there are still any IBController processes running, you'll have to kill them manually using Task Manager. You might think that ending a task via the Task Scheduler will end the relevant process, but this is not necessarily the case with Windows 10 and WIndows Server 20126 (you have to set the task up in a special way to work properly under these OSs).

5. When you are sure that there are no IBController processes running, then run an instance that has given you this problem.

6. If the problem still occurs, then attach the following information:

* the IBController log file
* the IBController.ini file (blank out your username and password)
* the relevant IBControllerGatewayStart.bat file
* the relevant IBControllerStop.bat file

**Comment by midasSSS** [comment]
I have checked again no instances are running. 


[IBControllerPPP.zip](https://github.com/ib-controller/ib-controller/files/1609218/IBControllerPPP.zip)

**Comment by rlktradewright** [comment]
Ok, now you're just wasting my time. I gave you explicit instructions about what to do, and what to send me, and all you can say is 'no instances are running'.

If you want me to help you, you have to send me the information I asked for.

**Comment by midasSSS** [comment]
I have attached ZIP to my previous post with all the files you asked for

**Comment by rlktradewright** [comment]
Thanks for the info.

You files look consistent. I notice from the log that you've been trying various port numbers, and they all work except for the last time: I presume that it was trying to use 7465, since that's what is configured in your .ini file (in the next release of IBController, I'll log the port number that it's attempting to use).

Now 7465 worked in an earlier attempt at 08:16:36:176 , so we know that there is nothing intrinsically 'funny' about this port.

And yet at 11:20:33:721 it no longer works.

this error message is telling you that something is already listening on that port. There is no possible misinterpretation of this, and there is no logic in IBController that could cause this message to occur other than in the situation it describes. It is simply a fact that something has got the port open.

Now we can see from the log that IBController closed down successfully after your first use of 7465 (just after 08:19:33). So since then, another program must have started that is listening on port 7465, You say that there are no other instances of IBController running at 11:20:33:721. If that is the case, then the only other possible explanation is that you have some other program running that is listening on port 7465.

So you need to find out what that process is. There is a simple command you can use to discover what is holding open a port (I intended to tell you about this a couple of days ago, but I couldn't make it work then, but I've now got it right).

So when you find yourself in this situation where the error message appears, start a command prompt and use this command:

`netstat -ano | findstr "7465"`

When I run this on my server (using 7462 instead of 7465 as that's what I use for my IBController port) I get output like this:

```
  TCP    0.0.0.0:7462           0.0.0.0:0              LISTENING       36524
  TCP    [::]:7462              [::]:0                 LISTENING       36524
```
The value in the last column is the PID of the process holding the port open. I can  look this PID up in Task Manager's Details tab, and lo and behold it tells me that it's a java.exe process. I can see from the Command Line column that it's an IBController process, though the command line is actually truncataed because it's so long, meaning that I can't actually see the ini file name.

So, over to you. You should now find it easy to discover the process that's holding open the port.
.

**Comment by midasSSS** [comment]
Thank you for comprehensive answer! 
I did what you just told and I again I found no instances running. However, I found out one very strange thing...

I have a few users, so inside IBController main folder I have sub-folders for users with different .ini and .bat files. So, I launched one user (from sub-folder) on port 7462. Then I tried to call Stop .bat inside the same folder and nothing happened (all bats try to close port 7462, for experimental purposes). Then, just for a last try I launched Stop .bat inside a main folder (so, one level up) and everything worked! 

What is happening and how can I fix this to have more convenient control over the users files?

**Comment by rlktradewright** [comment]
The STOP.bat file makes use of a VBScript file called SendIBControllerCommands.vbs. STOP.bat expects this file to be located in a Scripts subfolder of the folder from which it's run.

So if you're running Stop.bat in C:\IBController\auser, this file needs to be in C:\IBController\auser\Scripts.

Probably the best way to fix this is to change STOP.bat so that you don't need to create this subfolder. So do as follows (I'll include these changes in the next release of IBController):

1. Add these lines just before the :: IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:

```
:: You may need to change this line. Make sure it's set to the location of the 
:: IBController files:

set IBC_PATH=%SYSTEMDRIVE%\IBController
```

2. Replace this line:

`cscript Scripts\SendIBControllerCommands.vbs`

with this:

`cscript %IBC_PATH%\Scripts\SendIBControllerCommands.vbs`


Now it should be alright.

**Comment by midasSSS** [comment]
Perfect, finally we resolved this! 
Thank you very much, for patience and professionalism!
