### ISSUE TITLE
Using ssh forwarding - The remote host closed the connection

### ISSUE THREAD

**Issue by ibizaman** [ib-controller/ib-controller#22]
Hi,

I know this is strictly speaking not relative to ibcontroller but since you mention this tip in the README itself, maybe you already tried this method and already stumbled and overcomed the problem I have.

So I would like to connect to the ibgateway running on a remote server thanks to ssh forwarding. On the client where I want to connect the API, I run this command:
``` bash
$ ssh -L 4001:localhost:4001 me@192.168.1.2 -N
```
The ssh connection is established but when trying to connect the API, I get an error (retrieved by the EWrapper method "error"):
```
id: -1, errorCode: 502, errorString: The remote host closed the connection
```

To debug this, I tried:
* connecting to the ibgateway from the server itself and it works.
* forwarding something else like the webserver running on the server machine and it works:
``` bash
$ ssh -L 4001:localhost:80 me@192.168.1.2 -N
$ curl localhost:4001
```
This outputs the correct html page.
So for me, the ssh tunnel works as expected and the ibgateway also. But there must be something I'm missing. Do you have any idea what could it be?

Here is my .ini, in case it could help:
```
LogToConsole=yes
FIX=no
PasswordEncrypted=no
FIXLoginId=
FIXPassword=
FIXPasswordEncrypted=yes
StoreSettingsOnServer=no
MinimizeMainWindow=yes
ExistingSessionDetectedAction=primary
AcceptIncomingConnectionAction=accept
ShowAllTrades=no
IbAutoClosedown=no
ClosedownAt=
AllowBlindTrading=yes
DismissPasswordExpiryWarning=yes
DismissNSEComplianceNotice=yes
IbControlFrom=
IbBindAddress=127.0.0.1
CommandPrompt=
SuppressInfoMessages=no
```

**Comment by shevkoplyas** [comment]
That is strange. I just checked your tunnel command by trying similar one between 2 ubuntu boxes.

Here the box 1 where we can see 2 TWS running (one real account, other paper)
root@playbox:~# netstat -nap | grep java | grep LIST
tcp6       0      0 :::1234                 :::*                    LISTEN      28983/java
tcp6       0      0 :::1235                 :::*                    LISTEN      28915/java

as a client lets install IBpy by following this:
http://www.quantstart.com/articles/Using-Python-IBPy-and-the-Interactive-Brokers-API-to-Automate-Trades

Lets create tunnel from client (listening on std port 7462 so we don't need to modify python examples) to the playbox (which runs 2 TWS java apps on :1234 and :1234 ports)
ssh -L 7496:localhost:7462 dmitry@playbox -N

# verify it is listening:
root@107.22.85.198 us-east-1c:~/dev# netstat -nap | grep 7496
tcp        0      0 127.0.0.1:7462          0.0.0.0:*               LISTEN      29429/ssh
tcp6       0      0 ::1:7462                :::*                    LISTEN      29429/ssh

ha! it even listen on ipv6! Anyways.. keep going..

Now run an example (works fine via tunnel):

root@107.22.85.198 us-east-1c:~/ibapi/IbPy/demo# ./fancy_marketdata
Server Version: 71
TWS Time at connection:20150331 00:15:35 UTC
<managedAccounts accountsList=DU112189>
<nextValidId orderId=2361>
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:cafarm>
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:usfarm>
<error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:fundfarm>
<error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:ushmds>
Contract Values:EUR,CASH,IDEALPRO,USD,,0.0,:
* * * * REQUESTING MARKET DATA * * * *
<error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:cashfarm>
EUR:: bid: 1.0829
EUR:: ask: 1.08295
EUR:: bid: 1.08285
EUR:: ask: 1.0829
* * * * CANCELING MARKET DATA * * * *
<error id=-1, errorCode=2108, errorMsg=Market data farm connection is inactive but should be available upon demand.cashfarm>
<error id=-1, errorCode=2108, errorMsg=Market data farm connection is inactive but should be available upon demand.cashfarm>
root@107.22.85.198 us-east-1c:~/ibapi/IbPy/demo#


I had to modify the above example "fancy_marketdata" because it was giving me "<error id=1, errorCode=200, errorMsg=No security definition has been found for the request>" which actually was good enough to see that actual communication took place via the established tunnel. So I commented out this line:

    #contractTuple = ('QQQQ', 'STK', 'SMART', 'USD', '', 0.0, '')

and uncommented this one instead:

    contractTuple = ('EUR', 'CASH', 'IDEALPRO', 'USD', '', 0.0, '')

The whole "fancy_marketdata" script can fit 1 screen.. all simple and readable.
Try to install IbPy (takes 3-5 minutes) and run those demos first locally (on the same box where you run IBGateway or TWS) and then remotely via ssh tunnel).

hope it will help to isolate the problem.

Dmitry Shevkoplyas

**Comment by rlktradewright** [comment]
So as I understand it, you are trying to connect to the API on the gateway over an ssh tunnel. You are not trying to connect to IBController's command server.

If that's correct, then yes indeed this really isn't anything to do with IBController, so this really isn't the right place to ask the question. Just to be absolutely clear, IBController has nothing whatever to do with API connections - it knows nothing about them and does not intervene in any way when an API client connects to TWS/Gateway.

However, my off the cuff response is that you possibly just haven't configured the IP address of your source machine as a trusted IP address in the API settings.

**Comment by shevkoplyas** [comment]
Richard,

There's no need to configure source IP address as trusted since it will be localhost as if running on the same machine (due to the nature of the tunnel). This feature allows to automate remote connection even if you don't have permanent IP address btw.

**Comment by rlktradewright** [comment]
Oops, yes, sorry Dmitry, wasn't thinking straight. I must remember to engage brain! Difficult at my advanced age!

**Comment by ibizaman** [comment]
@shevkoplyas I installed IbPy (nice little program btw!) and tried to follow your steps but I think I'm missing something.

In my setup, the server (192.168.1.2) is running one paper instance of TWS:
``` bash
$ netstat -nap | grep java | grep LIST
tcp6       0      0 :::4001                 :::*          LISTEN      4096/java
tcp6       0      0 127.0.0.1:7464          :::*          LISTEN      4096/java
```
It looks already different than the output of your command: here I have the TWS instance listening on port 4003 and (I suppose) the IBController command server listening on port 7464.

Then you create the tunnel but I don't get the correspondance between what you say in the text and the command you pasted:
> Lets create tunnel from client (listening on std port 7462 so we don't need to modify python examples) to the playbox (which runs 2 TWS java apps on :1234 and :1234 ports)
ssh -L 7496:localhost:7462 dmitry@playbox -N

Where do you get your 7462 port? Is that the IBController command server like the 7464 for me? In that case, I don't get why you forward to that port, I would say in your case that the command should be: `ssh -L 7496:localhost:1234 dmitry@playbox -N` ?

Nevermind, I tried the two following tunnels:
```
ssh -L 7496:localhost:4001 me@192.168.1.2 -N
ssh -L 7496:localhost:7464 me@192.168.1.2 -N
```
In the first case, IbPy said it is not connected: `<error id=-1, errorCode=502, errorMsg=Couldn't connect to TWS ...>` while my application said `[error] id: -1, codeInt: 502, errorString: The remote host closed the connection`.
In the second cas, IbPy simply blocks on the `.connect()` method while my application is a little bit more chatty: `[error] id: -1, codeInt: 502, errorString: Protocol not supported`.

Sorry for nitpicking your post but I'm frankly going crazy right now. :)

@rlktradewright You're totally correct. This has nothing to do with IBController but since the ssh tunnel process was mentioned in the README I thought somebody could easily spot my mistake.

**Comment by rlktradewright** [comment]
ibizaman, I'd be grateful if you could point out to me where in the README (or anywhere else for that matter) it mentions ssh tunnels.

**Comment by shevkoplyas** [comment]
@ibizaman : Pierre, you're absolutely right, the command should be "ssh -L 7496:localhost:1234 dmitry@playbox -N" I did typo since originally trying to find quick reproducible client I tried ruby binding (I'm big fan of ruby, and python is a bit alien to me) and ruby didn't fly easy so I had to find other alternative, like IbPy (I don't use it, but it was good for quick and easy "out of the box" working example).

Re port :7464 - you're also right, most probably it stands for IbControllerPort (which you can verify by your .ini file). Btw, strange that I don't see this value in you .ini file that you posted in your original question under "Here is my .ini, in case it could help:". So don't mess with this port, lets forget about this port for now.

Now let us do 4 steps:

1) verify/change API port
by looking at your TWS or IBGateway that API is using port 4001 (as listed in your netstat output)
You might wanna change your API port 4001 to whatever was mentioned earlier as default for IbPy examples (or quickly glance through their sources to find out what they expect by default) or you can modify IbPy to accommodate your port properly. I'd suggest to use same std port on both ends just to avoid some simple errors

2) try to run IbPy example locally on the very same host before introducing the tunnel to make sure it is working correctly on one box. My guess - this step will fail on you. There's no point to move forward until your client app is working properly locally on the same box

3) double check you can ssh from your "remote" box into your "API listening" box with your credentials (ssh is not blocked by some firewall rules and credentials are good)

4) after ssh works and your client is happy locally (locally to listening API port) you can try to move your client to the other (remote) box by introducing the ssh tunnel. Imho ssh tunnels are there for so long that they're reliable as AK-47 if not more. And this step should not introduce any new obstacles after you solved previous step 2)

Also I'd suggest to use verbose "-v" mode in your ssh tunnel command. In this case your tunnel terminal might give you some hints on what is going on under the hood. Here's example output
----------------------- (example output) -----------------------------
dmitry@54.215.80.80's password:            <-----  here I typed password
debug1: Authentication succeeded (password).
Authenticated to 54.215.80.80 ([54.215.80.80]:22).
debug1: Local connections to LOCALHOST:7496 forwarded to remote address localhost:1234
debug1: Local forwarding listening on ::1 port 7496.
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 7496.
debug1: channel 1: new [port listener]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.

 <--------------- at this moment ssh tunnel is established and I'm about to run IbPy example
 <-------------- running ~/ibapi/IbPy/demo# ./fancy_marketdata here

debug1: Connection to port 7496 forwarding to localhost port 1234 requested.
debug1: channel 2: new [direct-tcpip]

<---------------- python pumping some data and working about 15sec before termination
<--------------- and now closing connection and finishing ./fancy_marketdata app 

debug1: channel 2: free: direct-tcpip: listening port 7496 for localhost port 1234, connect from 127.0.0.1 port 55772, nchannels 3
----------------------- (end of example output) -----------------------------


After you've established the tunnel with the following command:
ssh -L your_local_port:localhost:remote_api_port  username@remote_ip  -N
make sure (in other terminal) that is is listening locally by:

lsof -i :7496
COMMAND  PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
ssh     3632 root    4u  IPv6 15086461      0t0  TCP ip6-localhost:7496 (LISTEN)
ssh     3632 root    5u  IPv4 15086462      0t0  TCP localhost:7496 (LISTEN)

and run IbPy example on your "remote". I wonder when if fails?-)

hope it helps,
Dmitry

**Comment by ibizaman** [comment]
Unfortunately your guess on step 2 is incorrect.

In fact I was going to write a long post about what I tried but in the meantime, I resolved the problem. The solution is simple but quite disappointing at the same time.

See that `localhost` in the ssh tunnel command? Well, in fact that's the problem. When using `127.0.0.1`, it works fine... So the correct command is for me:
```
ssh -L 7496:127.0.0.1:4001 me@192.168.1.2 -N
```
I can understand, from a programmer point of view, that if there's a bind on "127.0.0.1" in my config it requires the exact same match. But still, why is it working for you then?

@rlktradewright I am very sorry. You are completely right. I saw it on [ibcontroller-aur](https://github.com/benalexau/ibcontroller-aur)'s README.

**Comment by shevkoplyas** [comment]
hm.. interesting! I'm glad you have figured that out!

I've googled "127.0.0.1 vs localhost" and actually there's a subtle difference between those, but in my case (I've just checked) both commands work the same similar way:
ssh -L 7496:localhost:1234   dmitry@54.215.8.8 -N
ssh -L 7496:127.0.0.1:1234  dmitry@54.215.8.8 -N

I also tried to compare verbose output of those 2 commands, but they're absolutely exact same.

which OS you're using on your 2 machines? I'm using Ubuntu 12.04 boxes

D

**Comment by ibizaman** [comment]
In both case I'm using Archlinux, up-to-dated as of now.
And both -v output are the same too.

Maybe my host.conf file is posing problem, (see SO answer)[http://stackoverflow.com/a/7382629/1013628]. Indeed, I'm using avahi so had to tinker with it but I'm not an expert enough to know if there's something wrong.

Anyway my problem is now solved. Thanks a lot!
