### ISSUE TITLE
Login with a security code card?

### ISSUE THREAD

**Issue by ibiza240** [ib-controller/ib-controller#25]
Is there any plan to support the security code card login window?

It would require a custom config of course that would represent the whole security code card...

so this window can be handled :

![Security code check](http://i.imgur.com/AGCavEI.png)

It is normally used with such a card :

![Security code card](https://ibkb.interactivebrokers.com/system/files/image/bingo2(1).gif)

Thanks!

**Comment by benalexau** [comment]
Hi

This won't be approached due to:

1. It violates the spirit of (and any assurances provided by) IB's security program. A compromised computer would allow login despite the user and/or IB having required a security token.

2. Even if an account is enrolled in the security program (eg my accounts are) it is permitted to create a secondary login for trading access. The primary login requires the token and that is needed for account management (including important matters like funds transfers). The secondary login can automatically login using IBController, but it cannot access account management. Therefore there's a reasonable approach that balances convenience and safety for automated trading systems, and users are free to use a secondary login or not as they individually determine.

3. It would be difficult to implement from an engineering perspective anyway, particularly for the physical tokens (eg I have a smartcard-based hardware token from IB). Sure you could tackle it easily enough for the print-friend security card (eg parse the PDF and read the dialog box text field), but it's much safer if you print the security card and store no copy of it on any computer.

The above policy has been reflected in the [contributor guidelines](https://github.com/ib-controller/ib-controller/blob/master/CONTRIBUTING.md) for some time. I hope the above explains some of the reasons. As such I will close this issue.

**Comment by ibiza240** [comment]
Hi and thanks for your reply!

I understand all of this and its perfectly fine.

I did not know I can request a secondary login, I will ask for one for sure and the problem is solved.

Best regards

**Comment by benalexau** [comment]
You can read IB Knowledge Base article, "[Adding a second user for an individual account holder](http://ibkb.interactivebrokers.com/node/1004)" for more information on the process.

**Comment by ibiza240** [comment]
Thank you very much :)

**Comment by Paw2Pom** [comment]
I have just applied for a 2nd username account with limited access (i.e. can only trade, but can't do fund transfer and other important stuff), and when I log into Client Management of this 2nd username account now, it asks me to apply for either an IB key or a Secure Login passcode card.

Any recommendation on how I should proceed with this?

**Comment by fleuss** [comment]
Hello,

I have been using the IB API in headless mode thanks to IBController on a secondary account for some time, very happy with it. 

Now something has come up: My account is registered in Hong Kong, and the local regulator has forced brokers to have only 2-factor authorization, starting this month, so I can't use this system anymore, which will force me to completely revise my whole setup.

The general trend seems only towards more constraints and regulations of all sorts, and I would not be surprised if other jurisdictions follow in that direction, so am trying to think of ways to go about it.

Any ideas ?

**Comment by ghost** [comment]
If your local regulator is requiring you use 2FA, I'd first advise that you consider their reasons for doing so.

Once you've decided that you're comfortable avoiding it, you have two options.

The first is to try and get the numbers interpreted automatically, but watch out - the method of obfuscation they use can always change, and the last thing you want to do is rely on the assumption that this will always work. Note that I don't agree with this approach and it goes against the contributor guidelines, but it's such an obvious point that it feels daft not expressing it to demonstrate the technical downsides as well as the obvious security downside.

The second is to capture the number box, send it to a human user, who merely interprets the numbers and sends them back. Then do a lookup to translate those numbers to passphrases. If you do this via e.g. a Slack bot, it's just a simple task for a member of the team to do when it comes to login time - read the image, and reply with the numbers. You'll probably want some handling in case the numbers are rejected, etc. It'd be advisable to have those numbers stored encrypted elsewhere, and for the trading machine to request the parsing, to emulate the secure nature of 2FA. This way, you authenticate with your credentials, a user signs off the running of the program, and a separate machine acts as the final authenticator. If someone has broken into your office and stolen your trading machine, a team member can prevent startup by not responding to the captcha.

This is a method once employed by spamming companies early days of the ReCaptcha project - copy the image, send it to a central database, and have a team of low paid workers who would get paid per thousand interpretations. Such a project proposal once landed on my desk, but I was never interested in assisting spammers - for something like this, though, there is a legitimate use for it.

This kind of, but doesn't quite, avoids the problem that the regulator is facing. They want traders to be responsible, to sign off on the opening of the trading application. This does that - a member is still entering the code, and it's still 2FA, it's just a case of automatically handling the conversion between numbers and passphrases, which isn't a necessary part of 2FA at all.

The better solution is for the members and users of this project to petition InteractiveBrokers to iron out some of the issues that the automation community faces in regards to their software - especially in the case you're in - 2FA being forced. Forced 2FA does **not** mean user intervention, it just means you need an additional source of authentication.

**Comment by fleuss** [comment]
Thank you for your response. I have thought a bit more about why I use this - this is my personal case - and what I really look for is the headless execution on a light, text-only system, rather than circumvent the security features for convenience. Right now IB sends me a SMS with a passcode, which I have to input in a graphic box in the GUI.

So rather than complicated solutions, all I would be looking for is a replacement to that graphic textbox: I would launch ibgateway through ibcontroller, then would get a text prompt asking me for the code sent to me by SMS, which I would manually input. I do not know how to do that, but based on what I read above it seems very doable, and also in the spirit of IBController, and also in the spirit of the regulator.

**Comment by webspiderc** [comment]
I am in HK and face the same issue as you do. My script is just broken for this reason. :(

**Comment by stnatter** [comment]
Hi guys. am facing the same problem with that pesky mandatory 2FA in Hong Kong. I do agree that any solution to read the screen and have a program put in the security code can proof elusive. And I full heartedly agree the we all need to lobby IBKR for a clean and efficient 'gateway' which actually allows automated trading. As it stands now the 2FA creates more risks for me as my trading system needs my attention to login. 
The best solution would obviously be a text based 'gateway' with secure RSA key login. That would be the only customer friendly solution. they should in fact have an interest in realising that as their API business keeps increasing and customers who trade through the API are more active. If European or US regulators impose a mandatory 2FA  they would have to come up with better solution quickly. Trouble is that there is no alternative to IBKR at the moment which is why they are so complacent.
Steffen

**Comment by rlktradewright** [comment]
It might be in your interest to read this post:

[https://groups.io/g/ibcalpha/message/570](https://groups.io/g/ibcalpha/message/570)
