### ISSUE TITLE
Issue with latest version - cannot start

### ISSUE THREAD

**Issue by creack** [ib-controller/ib-controller#27]
Hello,

I used to play with ibcontroller 2.12.0 and it works fine with latest version, however, when I try to upgrade to 2.12.2, I got this error: `Unsupported major.minor version 51.0`

**Comment by rlktradewright** [comment]
The internet is your friend! If you do a search for that message, you'll immediately find the answer.

But since I've taken the trouble to do that, I might as well save you the bother. 

You're using a version of Java that is way out-of-date. You should be using Java version 8.

**Comment by creack** [comment]
I am runing `jre-8u45`. I'll keep digging on the internet then.

**Comment by bcuster** [comment]
Don't know if this is the same issue but 2 days ago this came up:
I have Ubuntu box. I did auto-suggested upgrade from Ubuntu 14.04 to 15.04.
With 14.04 I had been running IBController 2.12.2 & TWS 9493 no problem using Oracle Java 8u25.
After upgrade to 15.04 I no longer had Oracle Java, it changed to OpenJDK, so I uninstalled OpenJDK & installed Oracle Java 8u45 -- the latest (TWS never worked with OpenJDK).
Now IBController will not launch TWS.  The process idles & I have to "kill -9 java" to stop it.
I tried reverting to Oracle Java 7, same behavior.
I can run TWS with either Oracle Java 7 or 8, but can't get IBController to launch it anymore.

The TWS logs log.day.txt, report these errors:

UIDefaults.getUI() failed: no ComponentUI class for: javax.swing.JTextPane[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,caretColor=,disabledTextColor=,editable=true,margin=,selectedTextColor=,selectionColor=,kit=,typeHandlers=]

java.lang.Error  	at javax.swing.UIDefaults.getUIError(UIDefaults.java:732)
   (followed by rest of the stack)

YH 01:28:51:108 AWT-EventQueue-0: Error
YH java.lang.NullPointerException   	at java.util.Hashtable.put(Hashtable.java:514)
   (followed by rest of the stack)

and then nothing else is written to the log.  The IBController log only mentions the NullPointerException.   When just running TWS without IBController, no error messages.

This makes me want to never use Ubuntu anymore, but it's an awfully big pain in the rear side to back everything up and reinstall different flavor of Linux from scratch.  But can't think of what else to do at this point, is there a preferred "most stable" Linux distro for IBController & TWS?

**Comment by rlktradewright** [comment]
[Ha ha, I never want to use Ubuntu (or any other Unix/Linux flavour) either - I've hated Unix since the mid-1980s. But I install a new version of Ubuntu every year or so, just to see if it's any less ugly and unpleasant than the previous release, and it never seems to improve...]

Let me make sure I'm not misunderstanding you. You're saying that you can run TWS on its own with no problem, but when you try to run it under IBController you get these errors?

This seems very peculiar to me. The fact that you are getting anything in the TWS log at all means that IBController has done its initial work and successfully loaded TWS into the process. At this stage, IBController is totally inactive and does nothing at all until TWS starts generating UI events. So I seriously doubt this problem has anything to do with IBController.

The errors seem to indicate that there is something wrong with your Java installation, because it appears to be unable to find the Swing components. Now if that's the case, then the only thing I can think of is that there is something incorrect about your java command that launches IBController: maybe the classpath (the -cp argument) is incorrect.

I've dusted off my 14.04 Ubuntu VM, and when it's finished installing hundreds of updates I'll try to upgrade it to 15.04 and see if I can reproduce your problem. 

By the way, no, there is no preferred flavour of Linux for IBContrroller - it should work fine on any distro where TWS works.

**Comment by bcuster** [comment]
Okay, well thank you very much for the look at it.
But, Yes, TWS executes & operates fine, takes my API calls, when I run with the IB recommended command line:
java -cp jts.jar:total.2013.jar -Xmx512M -XX:MaxPermSize=128M jclient.LoginFrame .

To IBController I use the IBControllerStart.sh, unmodified except for setting TWSDIR, IBCDIR & IBCINI, and I get the behavior described above.

At least I can run TWS, but IBController is crucial to my strategy! I suppose it is a Java install problem but I've tried installing Java 3 different ways & always same result.  Well, if anything turns up it'll be great to hear about it!

**Comment by rlktradewright** [comment]
Well I've just finished upgrading my Ubuntu VM to 15.04, and I'm hitting exactly the same problem you described (though I'm running OpenJDK). I haven't yet tried running TWS without IBController.

It's too late here in the UK to do any more now, but I'll take a closer look tomorrow.

**Comment by rlktradewright** [comment]
Well, I have to say I'm completely baffled at the moment.

First, it works fine if you run the IBController script under sudo. So there must be some kind of permission failure.

Secondly, the `UIDefaults.getUI() failed:: no ComponentUI class for` errors mean that the look-and-feel files that create the UI for the various Swing components can't be found (these might be custom files for TWS). 

Now, we know these look-and-feel files must exist, because they are found successfully when running TWS standalone, or when running TWS via IBController as root.

So it seems like there is a permission failure when running under IBController as non-root, but it can't be a failure to actually access the files, since they're the same files and the same user as when running TWS standalone.

The only thing I can think of that might explain it is that IBController hooks into the low-level AWT mechanisms for listening to UI events, and maybe this is subject to some security check within Java itself (and Java somehow recognises when you're running as root and then bypasses the check). This would explain why TWS runs ok standalone, because nothing is trying to hook the UI events.

I know that Java has its own security mechanisms, but I really know nothing about them, so perhaps I'll have to investigate them.

But what's really puzzling is why there should be a difference between Ubuntu 14.04 and 15.04. And since Java is cross-platform, why doesn't the same problem arise on Windows (where the latest Java version is fine). And if it's a Java-internal security fail, why don't the error messages reflect this? And why doesn't the failure happen when IBController declares itself as an AWT listener, which is way before it even loads TWS?

I'll have to come back to this later, as I now need to go and dig a deep hole - not for therapeutic reasons, though it may help, but because I have a badly blocked land drain on my property.

**Comment by rlktradewright** [comment]
A bit of progress here, just to keep you updated.

I removed the call to `Toolkit.getDefaultToolkit().addAWTEventListener()` in IBController  and now TWS starts properly when IBController is run non-root. Of course IBController is now effectively doing nothing, so the login frame is displayed as if IBController were not there and not handled automatically.

So at least this proves that it is IBController setting itself up as an AWT listener that is the initial cause of the problem. 

I'll have to investigate further when I've got a bit more time available.

**Comment by bcuster** [comment]
A peculiar problem for sure.  Ubuntu 15.04 is only about 6 weeks old, so presumably an unintended result of security upgrades to Ubuntu?

Great news there's a workaround with sudo though.  I don't know if this will help solve the issue, but for kicks I tried:
sudo -u dio ./IBControllerStart.sh

And TWS launched fully functionally.  'dio' is my regular user, however it is part of the admin group.  For whatever reason, executing "./IBControllerStart.sh" from dio's shell prompt creates the bug.

While it's awkward, at least can get back to normal operation here.  Again, big thanks for the help.  Let me know if I can help with testing, etc.

**Comment by rlktradewright** [comment]
I've finally discovered the cause of this problem.

Ubuntu 15.04 sets the JAVA_TOOL_OPTIONS environment variable to a value that causes the java-swing-ayatana project to be loaded whenever a Java Swing program is run. 

There is something about this project that causes Java not to be able to locate the Swing user interface components when IBController has registered itself as an AWT Window event listener.

I'll have to try and file a bug report with the java-swing-ayatana project about this. It seems that there are also several other programs that are adversely affected by the project.

The simple workaround is to add the line

`unset JAVA_TOOL_OPTIONS`

before the Java command in IBControllerStart.sh and IBControllerGatewayStart.sh.

[Note that when running Java as root via sudo, JAVA_TOOL_OPTIONS is not set. This explains why IBController worked properly when run under sudo.]

**Comment by shevkoplyas** [comment]
amazing! and so far from obvious!
Richard, you are The Great non-obvious-bug-hunter!!

**Comment by rlktradewright** [comment]
Actually, I was really rather lucky. I was about to post my first ever question to StackOverflow to see if anyone could throw any light on this, and then I noticed that whenever I ran Java under my user, it output a message to the console `Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar`, but it didn't do this when I ran as root using sudo.

Once I starting 'binging' (I don't like to use anything starting with the G-word!) for jayatanaag.jar, it soon became apparent what was going on. 

I've downloaded the code for the jayatana project, but it's probably not worth my time to try and work out why it interferes with IBController. By the way, the purpose of jayatana is to integrate Java Swing applications with Ubuntu's global menu and 'heads-up display' features. I have no problem with that, but it needs to be done in a way that doesn't interfere with other Java tool-like technologies such as IBController.

Interestingly, since discovering all this, I installed OpenJDK 8 on Ubuntu, and that version no longer emits this message. So it's quite fortunate I was using open OpenJDK 7, or I would never have made the connection (though perhaps someone on StackOverflow would have).

**Comment by kno10** [comment]
This is an Ubuntu bug: https://bugs.launchpad.net/ubuntu/+source/jayatana/+bug/1441487

**Comment by rlktradewright** [comment]
@kno10 I thought we had already established that . are you posting this just for interest or are you hoping for some further action?

**Comment by kno10** [comment]
The link allows people to follow bug fixing progress at Ubuntu.

**Comment by dandv** [comment]
Got the same "Unsupported major.minor version 52.0" error with Gateway 963.3g after configuring `TWS_MAJOR_VRSN=963` in `/opt/IBController/IBControllerGatewayStart.sh`.

![image](https://cloud.githubusercontent.com/assets/33569/26769382/69e83d6c-4963-11e7-965c-4d959386d9ee.png)

**Comment by rlktradewright** [comment]
@dandv 

This issue was closed two years ago. It related to a version of IBController that is no longer supports any current version of TWS, and was specifically related to Ubuntu 15.04.

So why try to drag it back to life? Much better to open a new issue (especially since it's most unlikely that the cause of your problem is that same as it was for this issue).

Also you haven't give any information at all that might help to diagnose the problem. So when you open a new issue, please include the IBController log file so I can see what's going on (attach it rather than quote it).
