### ISSUE TITLE
IBController does not start

### ISSUE THREAD

**Issue by mark1234s** [ib-controller/ib-controller#30]
Hi,
If this place is not the right to ask for help, please point to another
the message I receive when starting is: IBController: IBController: ini file "~/IBController/IBController.ini" either does not exist, or is a directory.  quitting...
The IBController.ini is in  home directory ~/IBController, the owner is the user with no admin rights
the shell file is in /opt/IBController
System: Ubuntu 14.04LTS,
this message support only images, I can't upload the .ini file to check

**Comment by rlktradewright** [comment]
The only thing I can see is that it looks like you've got: 

IBCINI="~/IBController/IBController.ini"

in your shell script. Try:

IBCINI='~/IBController/IBController.ini'

ie single quotes rather than double quotes (which is what the supplied shell script has).

**Comment by rlktradewright** [comment]
Oops, sorry, my mistake, those double quotes are put in the error message by IBController itself.

In that case, make sure the shell script does include the single quotes, in case you have one or more spaces in your username.

**Comment by mark1234s** [comment]
Hi Richard,
Thank you for the fast response. In the shell file, the .ini line is
IBCINI='~/IBController/IBController.ini'  and the other are
TWSDIR=/opt/TWS9493/IBJts
TWSCP=jts.jar:total.2013.jar
JAVAOPTS='-Xmx1024M -XX:MaxPermSize=256M' 

pushd $TWSDIR
# prevent other Java tools interfering with IBController
unset JAVA_TOOL_OPTIONS
java -cp  $TWSCP:$IBCDIR/IBController.jar $JAVAOPTS ibcontroller.IBController $IBCINI $TWSUSERID $TWSPASSWORD
popd
Also in the .ini file I want to start in demo mode with password encrypted, to see if the encryption is working. Next step will be to encrypt the folder but at this moment i do not know how.
IbLoginId=edemo
IbPassword=egpszylz -> this is the encrypted "demouser" passw
PasswordEncrypted=yes
IbDir=/opt/TWS9493/IBJts

**Comment by rlktradewright** [comment]
Well, first let me say that I'm not a Linux expert, and I don't actually know myself how to set up encryption (I know I really ought to, but as I don't use Linux for anything other than testing IBController to make sure it works, I can't justify spending time on it). However there seems to be plenty of help online.

Regarding your problem, I'm baffled as to why it isn't working. One thing that might help to diagnose it is that when IBController starts, it first prints out all the Java system properties. To capture this, you can redirect stdout into a file by appending > filename at the end of the java line in the shell script. Then run IBController, and paste the contents of filename (up to the second line of hyphens) here.

**Comment by mark1234s** [comment]
the output from the terminal(copy/paste):
/opt/TWS9493/IBJts /opt/IBController
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
System Properties
------------------------------------------------------------
java.runtime.name = Java(TM) SE Runtime Environment
sun.boot.library.path = /usr/lib/jvm/java-8-oracle/jre/lib/amd64
java.vm.version = 25.45-b02
java.vm.vendor = Oracle Corporation
java.vendor.url = http://java.oracle.com/
path.separator = :
java.vm.name = Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg = sun.io
user.country = US
sun.java.launcher = SUN_STANDARD
sun.os.patch.level = unknown
java.vm.specification.name = Java Virtual Machine Specification
user.dir = /opt/TWS9493/IBJts
java.runtime.version = 1.8.0_45-b14
java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
java.endorsed.dirs = /usr/lib/jvm/java-8-oracle/jre/lib/endorsed
os.arch = amd64
java.io.tmpdir = /tmp
line.separator = 

java.vm.specification.vendor = Oracle Corporation
os.name = Linux
sun.jnu.encoding = UTF-8
java.library.path = /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
java.specification.name = Java Platform API Specification
java.class.version = 52.0
sun.management.compiler = HotSpot 64-Bit Tiered Compilers
os.version = 3.13.0-55-generic
user.home = /home/usermark
user.timezone = Europe/Madrid
java.awt.printerjob = sun.print.PSPrinterJob
file.encoding = UTF-8
java.specification.version = 1.8
java.class.path = jts.jar:total.2013.jar:/opt/IBController/ib-controller-master/resources//IBController.jar
user.name = usermark
java.vm.specification.version = 1.8
sun.java.command = ibcontroller.IBController ~/IBController/IBController.ini
java.home = /usr/lib/jvm/java-8-oracle/jre
sun.arch.data.model = 64
user.language = en
java.specification.vendor = Oracle Corporation
awt.toolkit = sun.awt.X11.XToolkit
java.vm.info = mixed mode
java.version = 1.8.0_45
java.ext.dirs = /usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext
sun.boot.class.path = /usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes
java.vendor = Oracle Corporation
file.separator = /
java.vendor.url.bug = http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding = UnicodeLittle
sun.cpu.endian = little
sun.desktop = gnome
sun.cpu.isalist =

**Comment by rlktradewright** [comment]
Ok, I understand now, and it's all my fault!

In previous releases, IBCINI was set as follows:

IBCINI=~/IBController/IBController.ini

However if the username contained a space (eg John Doe) this caused a problem because that line got converted to:

IBCINI=/home/John Doe//IBController/IBController.ini

and this actually set IBCINI to /home/John, ignoring everything after the space (doncha just love Unix...).

So in the latest release, I changed the line to:

IBCINI='~/IBController/IBController.ini', thinking this would get converted to:

IBCINI='/home/John Doe//IBController/IBController.ini'

and all would be well. However this is not the case, because the ~ isn't actually substituted when it occurs within quotes! So the filename passed to Java is ~/IBController/IBController.ini, and Java treats it as a relative filename and fails to find the correct file.

Now for some reason this change didn't make it onto my Linux test system (carelessness on my part), so I never actually tested it. 

I can't think of a way to fix this in the script still using ~, so the best solution is probably to modify IBController so that it generates an absolute pathname before attempting to open the file. 

But in the meantime can I suggest that you edit the shell script to remove the ~ and replace it by /home/yourusername. It should work fine then.

Apologies for the crass mistake.

**Comment by rlktradewright** [comment]
I've now discovered how this should be done:

IBCINI="$HOME/IBController/IBController.ini"

The double quotes cause variable substitution in the enclosed string, whereas single quotes do not (but note that ~ is not substituted in either case). And the HOME variable contains the users home directory.

I'll issue a new release of IBController to fix this. I'll also look into amending the IBController code to get the absolute path from whatever is supplied, which might make life simpler for users who want to customise their scripts.

Unix is _great_! It always makes you work _so hard_!

**Comment by rlktradewright** [comment]
I've just published a new release with the amended shell scripts.

I decided against trying to do anything in the code to assist here. There is nothing that can be done in Java to handle ~ in file paths, since ~ only means something to the Bash shell and Java implementations seem to have no knowledge of it.

@mark1234s if you find this solves your problem, please close this issue.

**Comment by mark1234s** [comment]
yes, now it gets the absolute path, but there is something more:
IBController: IBController: ini file "/home/usermark/IBController/IBController.ini" either does not exist, or is a directory.  quitting...
I forget to tell you that at the beginning I tested with absolute path, and it gave the same error, so I leave the original. If you need again the system messages, I can paste them

**Comment by rlktradewright** [comment]
Well, at this point all I can say is that I now know exactly what filename it's looking for, and it isn't finding it. I know that the code makes the correct call to open the file. So that can only mean exactly what the error message says, the file doesn't exist.

To convince me that the file does indeed exist, you'll need to paste in a directory listing for /home/usermark/IBController.

I'll be away from the computer for a while, but probably not more than a couple of hours.

**Comment by mark1234s** [comment]
Richard, i am in big debt with you, when I listed in the terminal the directory, the folder does not appear, I was looking in the graphical interface and there did not recognize the missing t in the name. So now it is running, and please put in my account the drinks you like! Now have to study the question of encrypting the folder before changing to real account. Thanks again!

**Comment by rlktradewright** [comment]
Well actually I should be thanking you for finding a serious bug that I absolutely should have discovered myself. So next time you happen to be passing through Scotland we can buy each other a drink!
