### ISSUE TITLE
Is there any way to change IB gateway default config?

### ISSUE THREAD

**Issue by guidao** [ib-controller/ib-controller#40]
Hi, I want run IB gateway on headless server, but I could not change the default config, It will read config file from a random directory when IB gateway starting. I don't know this dir's name. when I restart it, it will create new dir. so, ib-controller can control  it ？

**Comment by rlktradewright** [comment]
I don't quite understand what you mean. In my experience the gateway never uses a random directory for its settings.

But yes, you can control which directory it should use with IBController. The `IbDir` setting in the ibcontroller.ini file specifies which directory to use.

**Comment by guidao** [comment]
Hi rlktradewright:
I set IbDir = "username",  I want auto configure IB gateway  "config->Api->Setting->Create Api Message log file". But I can't find that setting.

I get this message when exec ./IBControllerGatewayStart.sh :  
`19:45:57:358 AWT-EventQueue-0: Settings : loadFromXMLFile : Could not find settings file /home/dev/Workspace/cheetah/interactivebroker/bin/IBJts/username/darykqzus/ibg.xml`

but `darykqzus` name is a random string.

this is my username dir : 
➜  username git:(interactivebroker) ✗ tree .
.
├── darykqtv
│   ├── ibg.Wed.xml
│   ├── ibg.xml
│   ├── language.jar
│   ├── nia2.properties
│   ├── nia2.properties.bak
│   ├── nia2.script
│   ├── nia2.script.bak
│   └── Wed.rul
├── darykqvu
│   └── language.jar
├── ibgateway.Mon.log
├── ibgateway.Wed.log
├── jts.ini
├── locales.jar
└── xmlopt.dat

darykqvu don't have ibg.xml because I don't change IB gateway config by GUI.
IB gateway create new dir with random name when I run it again.

There is somthing I misunderstand. But I no idea know it.

**Comment by rlktradewright** [comment]
You can't configure the 'Create Api Message log file' setting with IBController. That's not what IBController is for. It's your responsibility to configure the Gateway as you wish. How you accomplish that is up to you. You basically have two options:

1. EITHER install some means of remotely accessing the Gateway GUI on your server. This makes a lot of sense, since the Gateway is very much a GUI program. You can remove the capability after you've finished configuring and testing the gateway, if you're concerned about security risks.

2. OR setup and configure the Gateway on a local machine with full GUI access, and then copy the setup to the target machine.

The error message you show indicates where the Gateway is looking for the ibg.xml, and that obviously isn't your user directory. So you must have set IbDir incorrectly: please read the comments in the .ini file on how to set IbDir correctly.

The folder names such as darykqtv as actually not random. If you logon with your live or paper-trading account, you'll find that it always uses the same directory (which will be a subdirectory of whatever you specified in IbDir). When you logon to the demo system, it chooses a directory name depending on which actual demo account is assigned to you, and this can be different for each demo session.

I suggest you forget your headless server for the moment and concentrate on understanding how to get IBController working on your local machine. Once you get that working, it should be too hard to do the same thing on the headless server.

By the way, I've tried quite hard to make the instructions for setting up IBController easy to understand. It's not an easy task! I realise that people might have trouble if English is not their first language. So if you have problems with any of the instructions (eg the User Guide or comments in IBController.ini etc) then please tell me so I can try and make it simpler.

**Comment by guidao** [comment]
Thank you very much.  I will give up to configure the IB gateway. ^.^

**Comment by rlktradewright** [comment]
Give up? Why?

I'm trying to help you, but I can only respond based on the information you give me. Was the information in my previous post of no use to you? If not, why not? What is it you need to know in order to proceed?

**Comment by guidao** [comment]
I want change the default config just for easy debug. It's not necessary. if it is hard to do this, I may be could use other way.

**Comment by rstms** [comment]
This sounds similar to a problem I'm working on...   guidao, are you using the 'edemo' / 'demouser' credentials?    I've found that with the latest version of TWS, when using the demo account a new 'random' config subdirectory is created on each startup of the java application.  I've just verified with IB tech support that this function is by design and specific to the demo account.  They said it is intended to force the demo account to always start with default settings, and to push users to configure a paper trading account.

**Comment by guidao** [comment]
@rlktradewright 
I am sorry for this. It's not random foldr name. Just because I use edemo account. Thank's  for your help.

@rstms 
yes, I use "edemo" account.  I found it's not random name. Thanks.

**Comment by xaduha** [comment]
@guidao Hi, sorry for necrobump, but I've run into the same issue with a random-ish folder name. You said you found out it wasn't random, what do you mean by that? Is there a way to override it and specify a fixed one?

**Comment by rlktradewright** [comment]
It's not random in the sense that every account will always use the same folder name. However there are many demo accounts, and when you login to 'the' demo account you are actually allocated one at random, which is cleanly initialised so that your demo session doesn't contain orders etc from someone else's.

So if you login to the demo account repeatedly, you'll gradually build up a whole set of these folders. Presumably it will eventually allocate you one you've used before. But you can never know which one you're going to get.

What are you trying to do that you need to know the name of this folder?

By the way, the answer to your actual question is that if you want to use a fixed folder, you have to use a real, funded account (live and paper get different folders, but always the same ones).

**Comment by xaduha** [comment]
I want to place ibg.xml before launching it first time and getting it picked up. I'm just interested in a way to either set it in some config file or get any idea of how that folder name is formed. It's pretty damn strange in my opinion to use this scheme, why not just use some date stamp that is predictable? Like config-live-16.08.2017 or config-paper-1502869698.

**Comment by rlktradewright** [comment]
Well, I have no comment on whether it's strange or not. I assume IB have a much better understanding than you or I of the forces that led them to this implementation, and it's been like that all the time I've been using TWS (since 2003). It's certainly not likely to change in the foreseeable future, so you'll just have to live with it.

It seems to me that you are only having a problem here because of using the demo system. For a live or paper system you can easily determine the folder name by observation. And for the demo system any such scheme is doomed to failure because the demo accounts are initialised to default values every time you log on, so I believe the contents of any existing 'funny name' folder are overwritten (but I haven't tested this assertion because I have better things to do).

But in any case, I question the wisdom of mucking around with the xml config files, because IB have changed their names, and their content, in the past and could do so again.

**Comment by xaduha** [comment]
Nevermind, I solved it with `inotifywait`.

**Comment by rlktradewright** [comment]
@xaduha 

Would you mind elaborating on that for the benefit of other users who come across this issue?

**Comment by xaduha** [comment]
````

inotifywait -m /root/Jts -e create,isdir |
    while read path action file; do
        echo "The file '$file' appeared in directory '$path' via '$action'"
        if [ "$action" == "CREATE,ISDIR" ]; then
          cp /root/Jts/ibg.xml /root/Jts/$file/ibg.xml
        fi
    done

````

works for me, might not work for others if there are some other folders expected to be made.

**Comment by rlktradewright** [comment]
An interesting idea. Just a couple of observations:

1. It seems to imply that if the ibg.xml file already exists in the newly created directory, the Gateway just uses it as it is. This negates my untested assertion made earlier, so that if you're allocated the same demo account as has been used previously, then you'll pick up any customisations made in the previous session for that account.

2. If you're subsequently allocated the same demo account, your script won't do anything because the directory will already exist. But you'll pick up the settings from the previous session. This may be what you want, or you may want to delete the funny directory after Gateway exits so you always start with a known setup.

**Comment by xaduha** [comment]
It's not about demo accounts, it's about running it headless in docker environment and disabling read-only mode. If read-only mode wasn't on by default, then it would be fine without ibg.xml.

**Comment by xge** [comment]
@jacktang presented a way to disable Read-Only API in #84.
