### ISSUE TITLE
Suggestion for better error tracking

### ISSUE THREAD

**Issue by fusiller** [ib-controller/ib-controller#45]
First a huge appreciation for your amazing work !

In TwsListener the function
    private static void logWindow(Window window,int eventID) 
might call  Utils.logWindowComponents(window)
if JLabel is "null" even if LogComponents is not set to yes
but that mightnot be a very good idea in fact

OR BETTER

the LogComponents option could be part of the IBController.ini template with some explanation.

In my case, trying to run IBGateway on a headless server, it took me a while understanding why the gateway was hanging until I browsed the code and found this great LogComponents option. Then I could just find out in the log file.

For your information my problem was :+1: 12:02:31:531 IBController: |   |   |   null(javax.swing.JOptionPane){JOptionPane: Fatal Error: one of the following jar files is missing from the classpath:
   rss.jar
Please make sure you run the application from the shortcut that was
installed on your desktop or on the Start menu when you upgraded.

The application will now terminate.}

**Comment by rlktradewright** [comment]
Thanks for your kind words of appreciation. I always like to point out that the basic groundwork for IBController was done by others back in the early noughties (and I wouldn't have had anything like enough knowledge of AWT back then to develop it from scratch). However I guess I've done enough to it since 2004 to accept some kudos!

You're absolutely right that `LogComponents` should be included in the IBController.ini template, and it will be in the next release. I originally kept it hidden on the assumption that anyone needing it would probably notice it in the source code, and the vast majority of users have no need of it except in special diagnostic circumstances - as happened a few days ago on the Yahoo TWSAPI group. But I realise now that it's much more sensible to make it fully visible.

**Comment by rlktradewright** [comment]
The `LogComponents` setting is now fully described in the specimen `IBController.ini` file.
