### ISSUE TITLE
2.14.0 fails to run on windows 10

### ISSUE THREAD

**Issue by webspiderc** [ib-controller/ib-controller#47]
Fatal Error: one of the following jar files is missing from the classpath:
   jfreechart-1.0.9.jar
   jcommon-1.0.12.jar
Please make sure you run the application from the shortcut that was
installed on your desktop or on the Start menu when you upgraded.

The application will now terminate.

Tried with 2.13.1, no such problem have been found

**Comment by rlktradewright** [comment]
This error message (from TWS) is very misleading: it was correct several years ago, but the mentions of jfreechart-1.0.9.jar and jcommon-1.0.12.jar are totally incorrect since neither of these files are used by IBController now.

What it actually means is that _some_ file needed by TWS is missing from the classpath, and this means that the line beginning `set TWSCP=` in IBControllerStart.bat is incorrect.

So please can you read the comments in IBControllerStart.bat that tell you how to set this line to the correct value. If you find it difficult to follow what I've written there, please let me know because I always want to try to improve things to make it as easy as possible to get IBController going.

**Comment by webspiderc** [comment]
Dear Richard
I have replaced the 2015b with 2012 then it works in my case.
set TWSCP=jts.jar;total.2012.jar

Many thanksBRCharles 


     On Monday, November 2, 2015 7:22 PM, Richard L King <notifications@github.com> wrote:
   

 This error message (from TWS) is very misleading: it was correct several years ago, but the mentions of jfreechart-1.0.9.jar and jcommon-1.0.12.jar are totally incorrect since neither of these files are used by IBController now.What it actually means is that some file needed by TWS is missing from the classpath, and this means that the line beginning set TWSCP= in IBControllerStart.bat is incorrect.So please can you read the comments in IBControllerStart.bat that tell you how to set this line to the correct value. If you find it difficult to follow what I've written there, please let me know because I always want to try to improve things to make it as easy as possible to get IBController going.—
