### ISSUE TITLE
IbAutoClosedown=no

### ISSUE THREAD

**Issue by alameda777** [ib-controller/ib-controller#49]
I have the configuration set to IbAutoClosedown=no, however TWS still keeps shutting down once a day despise having the setting ON. Can you please help?

**Comment by rlktradewright** [comment]
Since IBController always works faultlessly for me when I set `IbAutoClosedown=no`, I can't suggest anything offhand. You could help by supplying a bit more information, for example what version of TWS are you using?

You could also add this setting to the .ini file:

`LogComponents=yes`

This will place extra information in the TWS log file that enables me to see the structure of the various dialogs that IBController handles, so I can check if there's something unusual about your version of TWS (for example it's possible that IB have changed the structure of the Exit Session Setting dialog so that IBController no longer recognises it).

Then when TWS shuts down automatically, email me the last 10 minutes or so of the TWS log file. The log file is called log.Fri.txt (for Friday's log), and should be in the folder where you installed TWS (typically C:\Jts for Windows installations).

email it to rlking (at) aultan.com

Once you've done this, remove the LogComponents setting (or set it to 'no') to prevent the TWS log files getting too big (it also has a minor performance impact on TWS when it's on).

**Comment by alameda777** [comment]
Thanks Rich, after your comment I just rebooted my PC and now seems to be working fine
