### ISSUE TITLE
Additional prompt needs closing for Paper Trading accounts

### ISSUE THREAD

**Issue by ajpierce** [ib-controller/ib-controller#52]
In the latest version of TWS (954.2a), there is a new popup that forces you to acknowledge that you're using a paper trading account before TWS will connect to the API:

<img width="485" alt="screen shot 2015-11-28 at 9 00 57 pm" src="https://cloud.githubusercontent.com/assets/64226/11454984/d386a9c0-9613-11e5-90d3-2400b5209e2a.png">

Ideally, IBController will automatically press the "I understand and accept" button to complete the login process

**Comment by rlktradewright** [comment]
For a 'proper' paper trading account, as opposed to the demo system, this message is only displayed the first time you run TWS 954.2a, and I think it's perfectly acceptable for the user to see and respond to that message once (I presume nobody in their right mind would install a new version of TWS and not run it least once before subjecting their ATS to it). In any case, this message doesn't stop API programs connecting and operating normally (I say that advisedly as I haven't yet had a chance to place any trades against the paper system while this message is displayed).

It's not my policy to put in special code to deal with the demo system's peculiarities. Because IB give you a virgin system every time you login to the demo account, this message will always pop up.

**Comment by ajpierce** [comment]
Thanks for the quick response! I think this issue (and #51) are side effects of the fact that I'm trying to use TWS inside a [Docker](http://docker.io) container.

I will see if adding a TWS.xml config file from an instance that has already accepted all the prompts resolves this issue and let you know.

**Comment by ajpierce** [comment]
**Issue Resolved.** Want to confirm that I can get past this in Docker by taking the following steps:

1. Using VNC to your docker image, manually accept the prompt that says you're using a paper trading account.
2. `docker exec -ti <container name> /bin/bash` into the running docker image.
3. Navigate to the IB settings directory; for me, it was `/opt/IBJts/jars/dhmyhmeut/`
4. Copy the contents of `tws.xml.tmp` out to your project attempting to Dockerize TWS, and add it to your Dockerfile such that it gets added as part of the build process.

All subsequent Docker images built will no longer have to overcome IB's first-time logon messages.

Thanks @rlktradewright for pointing me in the right direction :)

**Comment by nmatare** [comment]
To follow up on this issue: I'm running TWS 955.4L without a docker. 

> _ 1. "this message is only displayed the first time you run TWS 954.2a"_

This error will continue to display regardless of whether you are logging in for the first time (and clicking I understand) or the nth time. It will subsequently prevent the user from expressing any functionality.

> _ 2. "In any case, this message doesn't stop API programs connecting and operating normally"_

I can confirm that this error WILL prevent API programs from connecting and operating normally. A connection error arises and the API is unable to execute commands. 

Currently, in order to facilitate paper trading, I'm getting around this by running TWS indefinitely. Not ideal, given the documentation :/

**Comment by rlktradewright** [comment]
There will be a new version of IBController soon that addresses this issue amongst other things. Probably next week.

By the way TWS 954 is no longer the 'latest' standalone TWS, which is now TWS 955.

Also if you just want to paper trade via the API, why not just use the 'stable' version 952 which doesn't have this behaviour?

**Comment by nmatare** [comment]
@rlktradewright Thanks, I'm looking forward to the new release!

Hmm, maybe I'm not finding the correction option, but version '952' doesn't support paper trading. At least its not listed normally on the main option screen.

**Comment by kunalkabra** [comment]
Hi, I am using latest version 968 but still facing the same issue.

Is there a workaround to this? (maybe using IBcontroller?). Unable to automate my entire process just because of this one step in between.

Please help!

**Comment by datatimeSRL** [comment]
This issue is really ridiculous. You make a GATEWAY that is supposed to run silently interfacing with automation, and * at every disconnection * you come out with a pop up ? And not just one, but even multiple on the screen!

Come on guys! This is completely retarded and you are damaging the traders using the gateway for development. You are also damaging my personal opinion about your intellectual capabilities.

Please, remove this stuff from the Gateway. I could live with 1 popup ONLY for the * very first * connection (which would be useless anyway, as people using the gateway are definitely not retarded and know perfectly what they are doing), BUT please remove the other pop ups at each connection, or give the option to disable it.

Seriously, IB,, this is very retarded and damage your very interests.

**Comment by kunalkabra** [comment]
Well, upgrade your IB controller to the latest version and add 
1. "AcceptNonBrokerageAccountWarning=true" 
2. "TradingMode=paper"
parameters to your ini file. It should solve the issue

**Comment by datatimeSRL** [comment]
Thanks for the kind reply kunalkabra. 

I installed the latest version Build 971.1a, May 7, 2018 9:33:30 A, and I did not see the issue anymore. I am glad they removed this stuff in the default install.

There is, sometimes, still the re-login confirm popping out under some conditions (eg, see ET thread: https://www.elitetrader.com/et/threads/interactive-brokers-issues-and-bugs-with-ib-gateway-9-63-and-with-api-9-73.320979/) but overall it seems acceptable (as far as it does not pop up on real $ or paper trading).
