### ISSUE TITLE
Under linux it seems that installed java is never used

### ISSUE THREAD

**Issue by SKoschnicke** [ib-controller/ib-controller#62]
The user guide states

> This means that it is not necessary to ensure that Java is installed on your computer. It doesn't matter if it is already installed, but the IBController scripts won't use it.

However, the [help of the IBController.sh](https://github.com/ib-controller/ib-controller/blob/master/resources/Scripts/IBController.sh#L32-L35) says that the installed oracle java may be used:

> javaPath -- Path to the folder containing the java executable to be used to run IBController. Defaults to the java executable included in the TWS installation; _failing that, to the Oracle Java installation_.

And the part of the script which should find the java installation [tests only for java included in TWS (twice)](https://github.com/ib-controller/ib-controller/blob/master/resources/Scripts/IBController.sh#L172-L188).

I think it is not enough to only use the java included in TWS, because the IBGateway download does not include java (at least I didn't find it).

**Comment by rlktradewright** [comment]
I had never realised there was a separate Gateway download. The gateway code is actually in the same jar file as the TWS code, with just a different entry point to start it (the two downloads could potentially contain different versions of the jar however). 

It's not exactly easy to discover the Gateway download. I could only find it by searching: one link took me to a specific Gateway download page, the other took me to the TWS download page. IB really need to sort that out a bit.

I'll have to update the User Guide to take account of this separate download.

The IBGateway download does indeed include java. It puts it in ~.i4j_jres.

The script doesn't test for the Java included with TWS twice: the two pieces of code are not identical. The reason for the difference is that if you install TWS/Gateway, then uninstall it, and then reinstall it again, for some reason it puts the location of the java installation into a different file. No idea why.

Regarding the use of the Oracle java installation (if any), the reason the script doesn't look for it is because I couldn't find an obvious way to locate where it should be, and I ran out of time before I set off on my week's travels. I'll have to try and improve this, and at least make sure that it does fall back to the Oracle java if the IB-supplied java isn't there.

**Comment by SKoschnicke** [comment]
You are right, there are really no separate applications for Gateway and TWS, this wasn't clear to me, thanks for pointing it out.

I was always using the download which I thought was the "Gateway Version", found here: https://download2.interactivebrokers.com/download/unixmacosx_latest.jar

I also haven't found a way to reach the download page for this when starting from the IB main site, but the URL for the download site was https://www.interactivebrokers.com/en/?f=%2Fen%2Fcontrol%2Fsystemstandalone-ibGateway.php%3Fos%3Dunix

Although the download URL looks official and current, the included version is 952.1e and there are really no unneccessary files present. Thats why I stated that Gateway didn't include java, the version I had really did not.

I think it would already help if a link to the "right" download page for TWS/Gateway is included in the userguide, as I found even that hard to find :) For example, when searching for a more current version of the download above, I found https://www.interactivebrokers.com/de/index.php?f=16044&ns=T, which looks like the current version, but uses a download script.

As for the issue of locating the java binary, I don't think that I have a universal way yet. I'm just using `dirname $(which java)` [in my own version](https://github.com/SKoschnicke/ib-controller/blob/269dbf6a844cc37dcfa546ef08cc0087fba9853e/resources/Scripts/IBController.sh#L181-L185), but I could come up with a more robust approach, at least for the linux case.

**Comment by rlktradewright** [comment]
I think putting a hard link to the TWS/Gateway download in the User Guide would be a mistake, as there's no guarantee that it would remain correct. IB seem to constantly change their website, and I also often find it annoyingly difficult to locate the downloads.

I also think IB are making a complete pig's ear of this. All they need is a single download (per operating system) that installs the desktop icons (on Windows) for both TWS and the Gateway, and with separate scripts on Linux: this would reflect the fact that they both use the same codebase, and would make everything simpler (and is very much how things used to be before the repackaging at TWS 952).

Regarding detecting whether Oracle Java is installed, this is easy on Windows (and the Windows script already does this). Thanks for the `which java` tip: my Linux 'expertise' is rather lacking! I think really all I need to do on Linux, having got the path, is to issue a `java -version' command and check the output to make sure that it's not OpenJDK (which causes problems for TWS).

**Comment by SKoschnicke** [comment]
You are right, it would be hard to provide a reliable link to the downloads. But I think IB is actually trying to only provide one application, although there is not yet an obvious way to start just the Gateway from that. All these "Gateway-Downloads" might be obsolete pages which nobody cared to clean up yet. But I acually like the "secret" link to the unix version I posted above, as it is just the jars and no installer or packaged java or something. I hope they keep it up to date to the latest stable version (which I learned is currently 952).

Maybe it would help if the user guide would contain some explaination about this confusing situation so that not every new user has to learn that it is indeed not as simple as one might expect to get the desired download of TWS.

I could extend the Linux script with the check you mentioned, if you wish. I'm happy to help :)

**Comment by rlktradewright** [comment]
I agree that it might be best to alert the User Guide reader to the need to take care in this area. This sort of thing is quite difficult though, because IB keep moving things about. I'll be doing some updates any way shortly so I'll take a look at it then.

Feel free to fix up the Linux script if you have the time. In my opinion, any time **not** spent working with Bash is time well spent!...

[One of these days I'll have to write an essay exploring the reasons for my deep-seated and decades-long aversion to Unix and its derivatives! Perhaps I should get therapy for it....]
