### ISSUE TITLE
Cannot disable Read-Only mode

### ISSUE THREAD

**Issue by andyflury** [ib-controller/ib-controller#65]
hello 

I'm using IBController 3.0.0 and IB Gateway  Build 952.1e, Oct 27, 2015

It seems like read-only mode is enabled by default and I cannot disable it.

Inside IBController.ini I set:
```
ReadOnlyLogin=no
```

But still I'm getting the following error when trying to place an order:

```
client: 0; request id: 25; error code: 321; error message: Error validating request:-'td' : cause - The API interface is currently in Read-Only mode.
```

I noticed that once the IBGateway is started up for the first time and properly shut-down (by sending "STOP" to port 7462) a new directory daryk... (the last few letters change every time) is created. This directory contains a file named ibg.xml. This file has some settings regarding the API:

```
<ApiSettings varName="api" dde="false" readOnlyApi="true" allowOnlyLocalhost="true" socketClient="false" autoOpenOrdDonwload="true" port="4001" includeFxPositions="true" includeContinuousUpdateChanges="true" sendMessagesInEnglish="false" sendMessagesTranslated="true" logLevel="2" useNegativeAutoRange="true" overridePrecautionaryConstraints="false" bypassBondWarning="false" bypassYtwWarning="false" bypassCalledBondWarning="false" masterClientID="-1" acceptLargeSize="false" showApiMsg="false" includeMktData="false" createApiMsgLogFile="false" showIBGConsole="false" aPINotAllowedShownAfterDenyAPI="false" slowBufferTimeout="30" syncAccounts="false" multichartNetDoNotShowTime="0" multichartDoNotShowTime="0" verifiedAppPortRangeStart="7000" verifiedAppPortRangeEnd="8000" timeOfVerifiedAppShutdown="0" portOfVerifiedAppShutdown="0">
```

As you can see there is a setting related to the readOnly:

```
readOnlyApi="true"
```

But obviously modifying the file manually does not sound like a good idea. Is there something that can be done through the IBController to disable the readOnlyApi?

Thanks
Andy Flury

**Comment by rlktradewright** [comment]
The `ReadOnlyLogin` setting is nothing to do with the read-only API mode. It governs whether a user who is enrolled in IB's security programme is prompted for their additional security identifiers when they start TWS via IBController: if set to `no` then the user must supply the additional credentials and the TWS login session is then not [read-only,](url) ie they can place orders etc via TWS (but not necessarily via the API). This setting is not relevant to the Gateway, since the user cannot place or modify orders via the Gateway user interface.

Whether the API is read-only is a different matter, and that is governed by an API configuration option in both TWS and the Gateway (the 'Read-Only API' option): use `Edit > Global Configuration > API > Settings` in TWS, or 'Configure > Settings > API > Settings' in the Gateway. IBController does not provide a way to set this, so you must configure TWS/Gateway manually to set it as desired (you certainly shouldn't be editing the TWS/Gateway settings files).

Note that if you login to the demo system, then you are presented with a 'virgin' API configuration each time, and so you will need to clear 'Read-Only API' each time you login if you want to user the API in non-read-only mode. But for real accounts (including paper-trading accounts) the setting is remembered between sessions, so you only have to set it when you need to change it (typically the first time you run TWS/Gateway).

Before you ask, I have no intention of providing a means to set this TWS/Gateway configuration option using IBController. The reasons for this have been extensively discussed elsewhere (eg see pull request #63), and I don't want to have to repeat them here.

**Comment by andyflury** [comment]
Thanks for the quick reply Richard

Yes, I'm aware that the 'Read-Only API' option can be turned off via the Settings dialog. Problem is that we are using a headless Linux server (using xvfb), so there is no Settings dialog to interact with. 

So it looks like modifying the ibg.xml is the only option we have at this time, is that correct?

Thanks for you help!

**Comment by rlktradewright** [comment]
If I were doing this, my approach would be:

1. Set up the Gateway on a non-headless local machine.
2. Configure it in the way I want (and don't forget that there are many configuration options in the Gateway that you many not want now, but may need in the future).
3. Test it thoroughly against my API programs.
4. Copy the entire JTS directory over to the target machine. 

I haven't actually done this, but I see no reason why it wouldn't work. If there is some reason why it isn't practical, please let me know.

**Comment by andyflury** [comment]
Ok thanks, I'll give that a try.

Do you have any idea what the naming logic is behind those settings directories (e.g. darykqzsm)?

**Comment by rlktradewright** [comment]
No, I've never had any insight into what the naming convention is. On my system, djkknie seems to be for the live account and djjifxfwn for the paper-trading account. And all the ones starting with darykq are for the demo account.

**Comment by tom3737** [comment]
Hi andyflury,

I have the same issue. In the IBController log, I get the message "API is in read-only mode". My trading script (which uses IbPy) shows the IB error: "error: <error id=None, errorCode=None, errorMsg=chr() arg not in range(256)>".

I am also using a "headless" machine. On another machine with TWS GUI, my script works fine.

Did you find a way to solve the issue? Did you try to copy the whole jts directory? I am hesitating a bit and I am still hoping that there is another solution.

Thanks,
Tom

**Comment by andyflury** [comment]
Hi Tom, I have not tried it yet, but I'm pretty sure copying the directory would work as suggested by rlktradewright, Regards Andy

**Comment by rlktradewright** [comment]
@tom3737 
 As far as I can see you only have two options:

1. As previously suggested: configure the Gateway on a local non-headless machine as you want it, and then copy the Gateway installation over to your target machine. You say you are hesitating a bit about this: why do you feel there may be a problem with it? It only needs to be done once.

2. Ensure that you have remote GUI access to the Gateway on your headless machine for the purposes of configuring it. Do a search on 'xvfb headless vnc' and you'll find quite a bit of info on this. Once you've got the Gateway configured, you can remove the VNC server to reduce the attack surface if you're worried about that.

**Comment by yongjae711** [comment]
I am using IB Gateway 952 with IB Controller 3.0.1, and copying the Gateway installation to my remote machine after disabling the read-only mode did not resolve this issue. I am still unable to send orders on my remote machine because the "API is in read-only mode", although I am able to send orders through the API on my local copy of IB Gateway. Is anyone else experiencing similar issues?

**Comment by rlktradewright** [comment]
Two possibilities I can think of:

1. You configured it for the demo account and copied that over. This is never going to work, because every time you start TWS/Gateway with the demo account it resets all the API settings, regardless of what you had set before. So you MUST configure it for your live account and copy that over.

2. You did configure it for your live account, but didn't copy everything over. In particular you need to copy over the directory where TWS/Gateway keeps its settings, which will be called something like ~/Jts/djkknie. The simplest thing to do is to simply copy ~/Jts/*.* and /opt/IBController/*.*. If you have more than one TWS/Gateway installation on your local machine, that will obviously be overkill, but it will ensure you get everything you need and the unnecessary stuff won't cause any problems on the remote machine.

**Comment by yongjae711** [comment]
Richard, both of the possibilities you mentioned are not occurring. I
confirm I am launching IB Gateway in live trading mode; it is not a demo
account. Also, I am using rsync -av to copy the contents of the Jts
directory from my local machine to my remote machine. Does anyone know why
this is occurring and how I can resolve this issue?

**Comment by rlktradewright** [comment]
Sorry for not responding again last night, but I went to bed just after my post (I'm in the UK).

Hopefully you've got it working now.

If not, the simple fact is that TWS doesn't store anything at all outside the Jts directory tree, so if you have faithfully copied that entire tree and all your IBController files, it cannot fail to work exactly the same as on the source machine.

I just did it between two Windows machines, and it was fine. I see no reason why two Linux machines should be any different.

It would be worth making absolutely sure it's logging in with the correct user id on the remote machine. Search in the Gateway log file (eg `~/Jts/ibgateway.Wed.log`) for the string "API Account:".

**Comment by yongjae711** [comment]
I resolved this issue by launching a GUI desktop session through VNC server
from my remote machine, connecting to the GUI desktop session my local
machine, installing IB Gateway directly on my remote machine, and disabling
read only mode.

**Comment by rlktradewright** [comment]
Ok. That's probably the easiest way to do it, but some people seem determined not to pollute their servers with anything GUI-related, so the copy approach should be ok for them. It's a shame we don't know what went wrong when you tried it, but not to worry.

**Comment by acuariano** [comment]
Will copying work if it's different platforms? I'm using a Windows workstation and I need to use headless IB Gateway in a Linux server (no GUI available).

**Comment by rlktradewright** [comment]
I don’t know – I’ve never tried it.

 

If you included the Gateway jar files in the copying, that almost certainly wouldn’t work, because the Windows jars aren’t the same as the Unix ones.

 

But if it’s just the settings files, they may well be compatible.

 

Personally, I wouldn’t take the risk. It’s very easy to set up a Linux virtual machine running on Windows using Virtual Box, Hyper-V or whatever, and then you can be sure you’re avoiding that risk.

 

If you haven’t set up a virtual machine before, then obviously there’ll be a learning curve, but it’ s not a steep one and is time well spent.

**Comment by acuariano** [comment]
I'll take your suggestion. I have created VMs before and that's why I wanted to avoid it. I don't have Virtual Box installed so it will take me a while to have a working Linux. But sooner or later I'll have to, so this is a good opportunity.
I'll post again if it works.

**Comment by jacktang** [comment]
Well, I am tired disable Read-Only API for demo account in remote server and patch it here(#84).

**Comment by acuariano** [comment]
Finally I got back to this problem this week. I tried doing the configuration in a VM with GUI and copying the Jts settings directory to the headless server and it worked. I tried looking to the diff between read-only and write-enabled and the found a readOnlyApi="false" in the file ibg.xml (tag ApiSettings). Tried changing only that, but doesn't work. Maybe IB Gateway checks for tampering?
In any case, copying the full settings directory from one instance to another does work.

**Comment by alexblickenstaff** [comment]
Has anyone figured out what exact file changes when the setting gets changed? I'm trying to create a properly configured Docker image from the standard TWS download so I need to know how to change the file(s) without actually opening TWS and manually changing it.

**Comment by rlktradewright** [comment]
TWS holds all its configuration info in a file called TWS.xml. You'll find it in a folder called something like djkknie (the actual folder name depends on whether it's a live or paper account, and other factors, but I'm sure you'll be able to find the right one).

**Comment by alexblickenstaff** [comment]
Thanks for the fast response. I assume this folder is in the root Jts directory (it seems to be there based on @acuariano's comment above)? I don't seem to have anything there; this is my folder structure in Jts:

```
root@b743c937eb92:~/Jts# ls -R
.:
961

./961:
Trader Workstation 961.desktop  jars  tws  tws.vmoptions  uninstall

./961/jars:
jts4launch-961.jar  log4j-core-2.5.jar  twslaunch-install4j-1.7.jar
locales.jar         total-2015c.jar
log4j-api-2.5.jar   twslaunch-961.jar
```

Perhaps it needs to be launched once to generate the configuration folder and the TWX.xml file?

**Comment by jaredbroad** [comment]
Hi @alexblickenstaff - I'd recommend using LEAN, we've solved a lot of this already using IBController. We pin the versions of IBController + IBGateway to keep things stable. https://github.com/QuantConnect/Lean/blob/master/DockerfileLeanFoundation

**Comment by alexblickenstaff** [comment]
Awesome, thanks. So does this mean the IBGateway installation you have hosted at http://data.quantconnect.com/interactive/ibgateway-latest-standalone-linux-x64-v960.2a.sh
is actually a modified version that has (perhaps among other things) the Read-Only mode set to false?

**Comment by jaredbroad** [comment]
Correct, its the fork at https://github.com/QuantConnect/ib-controller
built in ant for ubuntu with readonly api disabled.
