### ISSUE TITLE
IBController 3.0.0 failed to locate *.jar of IB Gateway 952 on Mac?

### ISSUE THREAD

**Issue by siuta** [ib-controller/ib-controller#66]
I installed IB Gateway Standalone verion (952) for Mac using this file 
https://download2.interactivebrokers.com/installers/ibgateway/stable-standalone/ibgateway-stable-standalone-macosx-x64.dmg

Once installed I've found the *.jar file are placed under ~/Applications/IB Gateway 952/jars instead of ~/Jts/952/jars

There's actually no such directory as ~/Jts/952/jars

Am I missing something obvious?

**Comment by rlktradewright** [comment]
No you're not missing anything obvious.

When I released IBController 3.0.0, I hadn't realised that there is a separate download for the Gateway (though I probably should have realised that there might be, and looked harder for one). This is because the jar file has always historically contained the code for both TWS and the Gateway (and that is still true - your Gateway download actually contains the TWS code too).

The workaround for this is to download and install the TWS download rather than the Gateway download, and everything will then work as expected. The only downside to this is that for any given account, the same settings files will be used for both TWS and the Gateway, so they'll both display the same set of tickers etc (and there could potentially be problems if you ran both at the same time, though I haven't tested this). However you can ensure they have separate settings files by using the `IbDir` setting in `IBController.ini` - so you would need separate `IBController.ini` files for TWS and the Gateway, with different values for `IbDir`.

The fact that currently there doesn't appear to be any way of locating the Gateway download except via a search indicates to me that IB haven't finally decided how they want to deploy the Gateway. I think it would be much better if they had a single download, which installed separate launchers (ie desktop icons or scripts) for TWS and Gateway (as has always been the case in the past). The only reason for having separate downloads that I can think of is that they might want to be able to develop them somewhat independently, but then why keep both code bases in both downloads?

Anyway I'll have to consider the best way to deal with this annoying situation - possibly just emphasise in the User Guide that it's best not to use the Gateway download, at least until I'm convinced that they have a stable approach.

**Comment by siuta** [comment]
TWS version 954 has the same issue.

*.jar file is under ~/Applications/Trader Workstation 954/jars 
tws-954.vmoptions is still under ~/Jts

I am going to change the IBController.sh myself. I think we don't need to change anything on Java source to accomodate two different path, right?

**Comment by rlktradewright** [comment]
Oh dear, it seems I didn't read your initial post closely enough. My reply was correct as far as it went, but for some reason I didn't pick up on the significance of the `~/Applications/IB Gateway 952` location for the jar file.

I think I'll have to modify the .sh scripts to detect the operating system and provide different defaults depending on whether its Linux or MacOS.

And yes, you're right that the Java source won't need to be changed.

**Comment by siuta** [comment]
for other reader - as a workaround I've created soft links to the jar file

**Comment by rlktradewright** [comment]
@siuta 

 Sorry for the delay in progressing this.

I don't have any access to a Mac, so please could you give me details of exactly where the TWS and Gateway installs put things?

Alternatively either paste your modified scripts here, or submit them as a pull reques,t or just email them to me at rlking at aultan.com

Thanks.

**Comment by siuta** [comment]
I just hardcode & create soft link as a workaround. So it's not generic enough for other people to use. Here's the info

**Path for Jar file**
jts.jar -> ~/Applications/IB Gateway 954/jars/jts.jar
locales.jar -> ~/Applications/IB Gateway 954/jars/locales.jar
total.jar -> ~/Applications/IB Gateway 954/jars/total.jar

Or replace "IB Gateway 954" by "Trader Workstation 954" for TWS

I didn't see a separate Java runtime just for IB Gateway. So I use the system one.

**Comment by rlktradewright** [comment]
Thanks, but my request wasn't clear enough.

I also need to know:

1. Where the .vmoptions files are and what they're called. Earlier you indicated:

    ~/Jts/tws-954.vmoptions

    but is there a different one for gateway?

2. On WIndows there is a C:\Jts\955\.install4j folder: where is the equivalent folder on MacOS?

When I have a modified script, would you be willing to test it for me?

**Comment by rlktradewright** [comment]
You said '_I didn't see a separate Java runtime just for IB Gateway. So I use the system one_'. 

However, I notice that when you download the Gateway for MAC via this link https://www.interactivebrokers.com/en/index.php?f=16457, the 'IBGateway Installation Instructions' page that appears says that _'A proprietary Java Runtime Environment is included with this package and may take a minute to install_'.

Could you check whether you have the latest version of the stable gateway, and see if your statement is still true? I must admit that the size of the current download (about 55MB) doesn't seem nearly big enough to include the Java Runtime, so I suspect you're right and IB is wrong.

**Comment by siuta** [comment]
-  About .vmoptions. the path for IBGateway is ~/Jts/ibgateway-954.vmoptions

- About .install4j, I didn't see that file. Here's what's under ~/Jts/
```
total 34552
drwxr-xr-x   2 Siuta  staff       68 Feb 17 22:33 charts
drwxr-xr-x  52 Siuta  staff     1768 Mar  2 08:20 dmsuipxvq
drwxr-xr-x  11 Siuta  staff      374 Mar  2 13:18 dwrykqzuvn
-rw-r--r--   1 Siuta  staff    51600 Mar  2 13:17 hs_err_pid46910.log
-rw-r--r--   1 Siuta  staff      722 Feb 17 21:10 ibgateway-954.vmoptions
-rw-r--r--   1 Siuta  staff  7421351 Mar  2 13:17 ibgateway.Thu.log
-rw-r--r--   1 Siuta  staff   255021 Mar  2 21:30 ibgateway.Wed.log
-rw-r--r--@  1 Siuta  staff      504 Mar  2 13:19 jts.ini
-rw-r--r--   1 Siuta  staff    12383 Feb 26 22:23 launcher.Fri.txt
-rw-r--r--   1 Siuta  staff    12663 Feb 29 22:17 launcher.Mon.txt
-rw-r--r--   1 Siuta  staff    16944 Feb 25 22:07 launcher.Thu.txt
-rw-r--r--   1 Siuta  staff    26027 Mar  1 22:23 launcher.Tue.txt
-rw-r--r--   1 Siuta  staff    19076 Feb 24 22:18 launcher.Wed.txt
-rw-r--r--   1 Siuta  staff    87394 Feb 23 20:38 locales.jar
-rw-r--r--   1 Siuta  staff  4082310 Feb 27 14:02 log.Fri.txt
-rw-r--r--   1 Siuta  staff  1515269 Mar  1 13:24 log.Mon.txt
-rw-r--r--   1 Siuta  staff   344101 Feb 27 16:11 log.Sat.txt
-rw-r--r--   1 Siuta  staff  1542684 Feb 26 13:24 log.Thu.txt
-rw-r--r--   1 Siuta  staff  1099758 Mar  2 08:20 log.Tue.txt
-rw-r--r--   1 Siuta  staff  1148767 Feb 25 13:24 log.Wed.txt
-rw-r--r--   1 Siuta  staff      724 Feb 17 21:05 tws-954.vmoptions
-rw-r--r--   1 Siuta  staff     3071 Mar  2 13:18 xmlopt.dat
```

-  If you have the modified script, I'm happy to test for you

-  I'm not able to find the java runtime under ~/Jts nor ~/Applications/* 954/

```
iMac:IB Gateway 954 Siuta$ ls -Rl ~/Applications/IB\ Gateway\ 954/ | grep java
iMac:IB Gateway 954 Siuta$ 

```

**Comment by rlktradewright** [comment]
Ok thanks for that. It certainly looks like IB haven't really got their act together yet with the MacOS downloads.

On the basis of this information I'll fix up the script as best I can and get it to you either later today or tomorrow (the latter is more likely). I'll probably do it as a  pre-release as there's quite a lot of other changes to go out and that will give others the opportunity to test it all.

**Comment by rlktradewright** [comment]
Ha, did I really say I'd get something to you to test 9 days ago?! Wishful thinking!...

There's been far more work to do for this next release than I anticipated, partly because of changes in TWS 955. In fact I haven't even got started on adjusting the scripts for MacOS.

And then on Wednesday my Windows 7 VM, on which I do all my IBController development, got corrupted and wouldn't start. So I spent all day yesterday restoring it from my system image backups, only to find today that I'd restored it to the wrong day! So now I'm having to do it all again today (only another 9 hours 55 minutes to go).

So I'm not going to make another prediction about when I'll have something ready. Thanks for your patience.

**Comment by siuta** [comment]
no worries. take your time.

**Comment by kamzik7** [comment]
First I would like to thank for a great tool! I had a similar problem with TWS on Mac OS X. The file structure on Mac OS X is different than the one expected by the scripts.

I modified the shell scripts and .ini file so they work now for me on OS X El Capitan with TWS 952.2h. Any feedback would be very welcome.
[scripts_for_macosx.zip](https://github.com/ib-controller/ib-controller/files/177148/scripts_for_macosx.zip)

I also attached the directory structure for a reference.

**Comment by kamzik7** [comment]
Directory structure for a reference attached.
[directory_structure.zip](https://github.com/ib-controller/ib-controller/files/177162/directory_structure.zip)

**Comment by rlktradewright** [comment]
@kamzik7 
Thanks very much for that. I still haven't got round to looking at the MacOS aspect, so hopefuly you've saved me some work! 

I'm doing some fairly significant refactoring to improve the IBController code, so it'll probably be a couple more days before I get onto the scripts.

**Comment by kamzik7** [comment]
Thank you for the response. I also tried on Linux Ubuntu 14.04 with TWS and I got: 

"TWS version 952 is not installed"

as the structure on Ubuntu is now also different to what scripts expects. Attaching the file structure for Ubuntu and example of the TWS execution.
[dir_structure_ubuntu.zip](https://github.com/ib-controller/ib-controller/files/177911/dir_structure_ubuntu.zip)

If you want I would be happy to create a new version of single script to handle the execution on both Mac OS X and Ubuntu for both TWS and Gateway. Let me know if you want to do it yourself or if you are ok with me preparing it. Take your time to look at my scripts and decide, no rush, I understand you are busy.

**Comment by rlktradewright** [comment]
No, the existing scripts work fine on Ubuntu.

I think what you've sent me is for the self-updating version, not the offline version, of TWS. IBController doesn't support the self-updating version.

**Comment by IAmBroom** [comment]
Ack, Richard, now I'm getting this error on an install of TWS on a new Windows 7 (SP1) system, too.
   C:\IBController\IBController.ini
   C:\Jts\952\tws.exe
   C:\Jts\952\tws.vmoptions

CONTENTS OF vmoptions:
_-Dinstaller.uuid=1312cca9-605d-460c-a78d-8024ea1fe4af
-DvmOptionsPath=C:\Jts\952\tws.vmoptions
-Dsun.java2d.noddraw=true
-Dswing.boldMetal=false
-Dsun.locale.formatasdefault=true _

Using TWS 952(.2j) dated March 21 2016 15:48:51, 32-bit:
   tws-stable-standalone-windows-x86.exe

**Comment by rlktradewright** [comment]
The ONLY change you need to make in the .bat files included with IBController 3.0.1 is this, in IBControllerStart.bat:

`set IBC_INI=C:\IBController\IBController.ini`

That's it! Nothing else! How can I make it any easier?

If you still can't make it work, then post the contents of your IBControllerStart.bat file here so I can see what you've done.

**Comment by IAmBroom** [comment]
Thank you. I had changed that, but I apparently also changed another line
at the same time. :\

**Comment by rlktradewright** [comment]
@siuta @kamzik7 and any other OS X users:

The new release issued today (3.2.0-beta.1) contains new .sh files specifically for OS X (I found that easier than trying to make single scripts to serve both Linux and OS X).

I'd be extremely grateful if you could find the time to test these with both the stable (952) and latest (955) TWS versions.

Thanks.

**Comment by kamzik7** [comment]
Thank you for the new version!  I hit some minor issues with the shell scripts, after fixing those I successfully tested with 952.2j and 956.2i.

The description of the issues and proposed fixes are at bit.ly/ibc_feedback - look at README file.

**Comment by IAmBroom** [comment]
On Sat, May 21, 2016 at 7:15 AM, kamzik7 <notifications@github.com> wrote:

> The description of the issues and proposed fixes are at
> bit.ly/ibc_feedback - look at README file.
>

Why are you spamming the list with an included ad for a brokerage?
("screenshot.png")

**Comment by kamzik7** [comment]
It was not intended as spam. It is a screenshot of an issue I described - if you look closer you'll see 'Attempt 2: Authenticating...'.

When I took the screenshot, I repeatedly could not login with ibcontroller while I could login manually, so at that time it looked as serious issue. I was asked directly for feedback and I provided it together with proposed fixes for issues. If you are not interested in my feedback, please don't follow the link. I intentionally provided the details through the link so that non-interested parties don't have to read it.

**Comment by IAmBroom** [comment]
My apologies. I didn't realize that was a big splash ad on the loading
screen you were capturing.

**Comment by rlktradewright** [comment]
@kamzik7 

Thanks very much for the feedback. I'll get another version out soon (not today though).

I think it would have been better if you had posted your experiences and your proposed changes directly here, rather than just providing a link. Non-interested parties don't have to take any notice of them, and why would they be reading this issue at all if they're not interested? The link is inconvenient for people like me who work on windows and don't happen to have a way of unpacking .gz files. I had to access the link via my Ubuntu virtual machine, unpack it there and then copy the files over to the Windows 7 machine where I do the IBController work: not a big issue, just a minor irritation.

**Comment by kamzik7** [comment]
Thank you for the advice, I'll post the files directly the next time!

**Comment by IAmBroom** [comment]
FYI: 7-Zip can unzip tar and gz archives.
