### ISSUE TITLE
'C:\Program' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by jpatton14** [ib-controller/ib-controller#68]
I just installed IBController 3.0.0 and TWS 954. When I run the start .bat file I get the following error. I'm able to fix it by changing the 5th-to-last line in Scripts/IBController.bat to begin with:
"%JAVA_HOME%\java.exe"
instead of
%JAVA_HOME%\java.exe

But let me know if there's something wrong with my setup.

Here's the error message I get:

Starting IBGateway with this command:
C:\Program Files\Common Files\i4j_jres\1.8.0_60\bin\java.exe -cp  C:\Jts\954\jar
s\jts.jar;C:\Jts\954\jars\total.jar;C:\IBController\IBController.jar  -Xmx768m -
Dinstaller.uuid=df4796f6-c414-4bf3-8c1c-151d76131bf0 -DvmOptionsPath=C:\Jts\954\
tws.vmoptions -DjtsConfigDir=C:\Jts -Dsun.java2d.noddraw=true -Dswing.boldMetal=
false -Dsun.locale.formatasdefault=true ibcontroller.IBGatewayController "\Users
\Joel Patton\Documents\Trading\IBController\IBController_ratan.ini" "" ""

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by rlktradewright** [comment]
You're quite right - the %s should be there. 

Interesting that the installation has located the i4j_jres folder in `C:\Program Files\Common Files`: in every previous installation I've done (including one with a fresh download yesterday afternoon) that folder has been placed in 'C:\Users\<username>' (which is partly why I didn't notice this problem before, though I'm just making excuses here!). I guess IB must have posted a new download since I did mine yesterday - I'll check it out.

In fact this is a much better location to store that file anyway: with the previous setup, TWS would only work for the user that installed it, but would fail for any other user on that computer.

**Comment by rlktradewright** [comment]
@jpatton14 

I've just downloaded the latest TWS 954 (version 954.2t Feb 16) from IB's website, completely removed the previous installations (of all TWS and Gateway versions, and the embedded Java), then installed TWS and once again (as before) it has placed the i4j_jres folder in `C:\Users<username>`, so that my start command becomes:

C:\Users\rlk.TW\.i4j_jres\1.8.0_60_64\bin\java.exe -cp  C:\Jts\954\jars\jts.jar;C:\Jts\954\jars\total.jar;C:\IBController\IBController.jar  -Xmx768m -Dinstaller.uuid=df4796f6-c414-4bf3-8c1c-151d76131bf0 -DvmOptionsPath=C:\Jts\954\tws.vmoptions -DjtsConfigDir=C:\Jts -Dsun.java2d.noddraw=true -Dswing.boldMetal=false -Dsun.locale.formatasdefault=true ibcontroller.IBController "\Users\rlk.TW\Documents\IBController\IBController.ini" "" ""

So I'm curious as to how yours comes to be different (not that it makes any difference to the fix you pointed out, it's just that I like to know what's going on!). 

Did you maybe use an older version of the download? Or did you perhaps move the i4j_jres folder to its more sensible place on your system and update the appropriate files? Or are you using a different Windows edition (all my installs were done on Professional editions - Windows 7, 8.1 and 10).

**Comment by jpatton14** [comment]
I'm not sure, I'm on Windows 7 Professional still. I accidentally
downloaded the online TWS version, then uninstalled and it installed the
offline version. I didn't move any of the folders around or change anything
else. I should note that my username on the machine is "Joel Patton" so I
think it would still suffer from the issue of having spaces in the path
name.

I did notice 1 other issue you could fix too. I invoke my
IBControllerStart.bat files via a separate process so the current working
directory when executed isn't C:\IBController. This causes the line final
line in this file: "call Scripts/IBController.bat" to fail because it's a
relative path. I think this should be changed to "call
%IBC_PATH%\Scripts\IBController.bat".

Lastly I have another question for you: other than trying to prevent TWS
from shutting down and keep it running is there any other mechanism for
bypassing the security token card authentication mechanism? My trading is
fully automated so I'm not available to enter the card key. IB recently
warned me that this program is becoming mandatory so I can no longer opt
out of providing the auth key. I haven't activated it just yet but was
wondering if IBController had any supporting for entering this key too.

And thank you for developing and maintaining this product too! I've been
using it for years and it's been enormously helpful!

Joel

**Comment by rlktradewright** [comment]
Ok, well I tried installing the online version on a virgin Windows 10 virtual machine (it had never had anything other than the operating system installed), and that still installed the Java in the same (silly) place. So I'm baffled.

Regarding the suggested fix for the relative path, good idea, I'll do that in the next release.

As for the security card, our policy has always been (and will remain) that we don't even attempt to bypass IB's authentication mechanism because IB confers benefits on the basis that the full authentication has been done. Bypassing it would be a serious breach.

If IB decides to make the cards mandatory, it will be a blow for the many users in the same situation as you (I'm one myself). How bad a blow I'm not sure - if it just needs the key entered once a week on a Sunday evening, that wouldn't be too bad, but having never had one myself I don't know what the worst scenario might be.
