### ISSUE TITLE
Various IBController Questions

### ISSUE THREAD

**Issue by bobgit3** [ib-controller/ib-controller#72]
(Apologies if a similar set of questions has appeared on the Yahoo IB TWS API Discussion group – I tried to post there first but after submitting it didn’t appear.)

I am attempting to use IBController version 3.0.0 with TWS offline version 952.2h (most stable current version as far as I can tell from IB website) on a Paper and a Live IB account running on a GoDaddy VPS.  I believe I have followed the User Guide correctly in installing 2x Jts, config, bat and Windows Task Scheduler files/folders.
 
1.	Noticed in the User Guide that it references Build 954.2a even though it also recommends using the latest standalone version (952.2h per IB).  What is current recommendation?  It seems that latest TWS standalone is version 955.4e.

2.	Even though I set up separate shortcuts from the application files in JtsLive and JtsPaper, it doesn’t seem to matter which I use, the TWS login screen Settings directory always comes up with the last instance I used. How can this behaviour be changed? (I have set StoreSettingsOnServer=no on both the Paper and the Live config files since the User Guide recommends it when you use multiple instances.  I have also used the “\\” format as directed for IbDir.)

3.	Use/store settings on server is always checked even though I have tried various settings in the Exit Options section of the Lock and Exit section of the TWS configuration settings.
 
4.	I don’t understand the significance of the config file section on automatically saving TWS settings on a schedule of your choosing.  Perhaps connected to the questions above?  Why, once everything is set up, do you need to keep savings settings at all?  And if you do, how do you recommend deciding between the various options presented?
  
5.	When I use Windows Scheduler to start IBController, it doesn’t appear on my GoDaddy VPS (Windows Server 2012R2) even though I have MinimizeMainWindow=no in my config files.  The only way I now for sure that TWS has started is that when I then try to login directly I am told that another instance is already running.  Can this behaviour be changed so that TWS is visibly opened in a window on the VPS desktop?

Thanks very much for your help.

Bob

**Comment by rlktradewright** [comment]
1. The reference to version 954 in the User Guide is just an example of a TWS version number. That was the version of TWS that  was installed when I wrote that line.  Whatever I put in there is eventually going to be out-of-date, so I can’t see that it’s of the slightest significance.

    You can use any version of TWS you like. The User Guide just brings to your attention that the latest version, as opposed to the latest stable version, is more likely to have bugs in it. 955.4e is not the latest stable version. Draw your own conclusions.

2. Regarding your attempt at multiple instances, you should have, for each instance, a XXXStart.bat and a XXX.ini file. The XXXStart.bat file must contain the location of the corresponding XXX.ini file in the line beginning ‘set IBC_INI=’. When you run the relevant .bat file, the corresponding instance should start. Does it? 

    I don’t know what you mean when you say you '_set up separate shortcuts from the application files in JtsLive and JtsPaper_’. JtsLive and JtsPaper shouldn't have application files, they’re settings folders. You could create shortcuts to the XXXStart.bat files (maybe that’s what you meant?). But make sure the XXXStart.bat files actually work before doing this.

3. This is evidence that you are in fact not using the correct XXX.ini files.

    The TWS Lock and Exit settings have absolutely nothing to do with which settings folders are used.

4. Regarding the scheduled save settings facility, this post is the original request for it: https://groups.yahoo.com/neo/groups/TWSAPI/conversations/messages/33953

5. As it says in the User Guide, to run TWS via Task Scheduler and for it to be visible, the relevant user **must** be logged in before the task is run. If the user is not logged in and the task is defined to start only if the user is logged in, then of course it won't even start. If it's defined to start whether or not the user is logged in, then if the user isn't in fact logged in, it _will_ start but it will be started in Session 0: this is a special session that has no associated window station, and is therefore never visible.

    I don't want to get into a tutorial about sessions, window stations and desktops, so suffice to repeat that if you don't ensure the computer is logged in before your TWS scheduled task runs, then you'll never be able to see it. So you need to ensure that it's logged in before the TWS task runs. Assuming you don't very often restart your VPS, this may not be too much of an inconvenience. However you can also set up automatic login when the server starts: how to do this is well documented elsewhere (using the AutoAdminLogon registry setting), though there are obvious security risks associated with it.

   However even if you do set up your server so that it logs in automatically to the user you want to run TWS under, you're not home and dry. You need to be able to remotely connect to the console session (session 1) to see TWS, and you may need to contact GoDaddy for how to do this (though I would imagine you'd get access to the console session by default).

    I run TWS on Windows Server 2012 R2 myself, so I'll explain how I do it. First, my server is actually a virtual machine that I run within a headless Windows HyperV Server. This means that I can access the console session using the HyperV Virtual Machine Connection client. I've set the VM up so that it automatically logs on at startup to a limited-permissions user, and TWS runs under this user. Part of the startup routine is to run a small utility that locks the screen and keyboard (through Windows API calls). This user is also set up to disallow connection via remote desktop. The end result is that there is no way to access this user session (and this user's data, eg the IBController.ini files) except via the HyperV Virtual Machine Connection client from another (physical or virtual) machine, which requires manual entry of a very unguessable 16-character password. 

   Whether you'd be able to do something similar with your GoDaddy VPS, I've no idea.

**Comment by rlktradewright** [comment]
In view of the lack of further comment, I'll close this now.
