### ISSUE TITLE
TWS version 952 is not installed

### ISSUE THREAD

**Issue by droter** [ib-controller/ib-controller#73]
Hi,

I am getting this message when running IBControllerStart.sh:
TWS version 952 is not installed

I have the directory in /opt/IBJts and I can start the jar file from there.  I checked the version 952.1e and also changed the TWS_PATH to =/opt/IBJts in IBControllerStart.sh

But still getting the error.

Any ideas?

Thanks,

Matt

**Comment by rlktradewright** [comment]
Your TWS version is way out of date: it may even be from before IB did their installation repackaging.

So please download the 'latest stable offline version' again and install that.

Then make sure you're using the latest IBController release, and use the script files from there (including the Scripts subdirectory) rather than trying to modify old scripts.

**Comment by joelpinheiro** [comment]
Hi, I have TWS offline 952,  TWS offline 955 and gateway 955.

I had downloaded the last version of ib-controller and unzip it to /opt/IBController.

When I run:
`sh Scripts/IBController.sh 955`

I receive the error:
'TWS version 952 is not installed'

Did I miss any step?

**Comment by rlktradewright** [comment]
Try using Bash.

**Comment by joelpinheiro** [comment]
I removed all the previous version. Now I have the following version:
```
Trader Workstation 955
(.4i) 20160316 15:50:03 ((.4i) 20160316 15:50:03)
```

I did
`/opt/IBController/Scripts`
and then
`./IBController.sh 955`

Error: `TWS version 955 is not installed`

If I run
`./IBControllerStart.sh`
From 
`/opt/IBController`
I receive
`TWS version 952 is not installed`

**Comment by rlktradewright** [comment]
Well I just uninstalled the TWS 955 version that was on my Ubuntu VM, downloaded TWS 955.4i, installed it and it just runs perfectly.

This might sound like a silly question, but I presume you have actually installed TWS, rather than just downloading it?

If you've installed TWS, and you've put IBController where you said, and you haven't modified the scripts, then it simply **MUST** work!

**Comment by joelpinheiro** [comment]
Yes. I had installed it.

Maybe it is a Mac-OS related issue. Anyone with this problem in this OS?

**Comment by rlktradewright** [comment]
The download page for the latest release of IBController says quite clearly:

> The scripts provided do not currently work properly with MacOSX (see Issue #66). 

An update to fix this will be issued in due course.

**Comment by jaredbroad** [comment]
QuantConnect/Lean users are getting this error in Windows 10 as well.

**Comment by rlktradewright** [comment]
Then they haven't followed the very simple instructions! Here's a summary of what you have to do:

* download and install the required **offline** version of TWS

* make sure the IBControllerStart.bat file contains the correct TWS major version number

* make sure the IBControllerStart.bat file contains the correct location for the IBController.ini

That's it! I don't know how to make it any easier. I'll describe these steps in more detail below, but first note the following:

_If you are trying to use a version of TWS 952 that you downloaded before about the end of October 2015, then you MUST download it again. TWS 952 has been updated since then and now installs in a different place: that old version of TWS 952 does not work with the current IBController._

So here's what to do in detail:

1. Download and install the version of TWS you want to use from IB's website. 

    **DO NOT USE THE SELF-UPDATING VERSION OF TWS, BECAUSE IBCONTROLLER DOES NOT WORK WITH IT.** 

    Use the version described as 'offline': thus on IB's TWS download page at https://www.interactivebrokers.com/en/index.php?f=14099#tws-software, download using either of the links entitled '**OFFLINE TWS LATEST**' or '**OFFLINE TWS**'.

    **DO NOT** use the links entitled 'TWS LATEST', 'TWS' or 'TWS BETA'.

    I've just noticed that IB are now promoting TWS 955.4 as their OFFLINE TWS LATEST'. I recommend you don't try to use this version at present, because IB have made some changes in it that will annoy you intensely: I'm working on a new version of IBController to make life easier. So stick with 'OFFLINE TWS', ie Version 955.2.

2. Edit IBControllerStart.bat so that it has the correct major version number. For the 'OFFLINE TWS' this will be version 955, so you should have:

    `set TWS_MAJOR_VRSN=952`

    For the 'OFFLINE TWS LATEST' this will be version 955, so you should have:

    `set TWS_MAJOR_VRSN=955`

3. Ensure that IBControllerStart.bat has the correct location for your IBController.ini file, in the line beginning `set IBC_INI=`.

4. Make sure that the line in IBControllerStart.bat that specifies where TWS is installed looks like this:

    `set TWS_PATH=C:\Jts`

    **Do not** change this line to include the folder containing the .jar files.

    There may be a few users who have their Windows installation on a hard drive other than C:. In this case, you also need to make sure that this line contains the correct drive letter.

Now run IBController. It will work.
