### ISSUE TITLE
Parameter parsing in configuration file should not be case sensitive

### ISSUE THREAD

**Issue by rterbush** [ib-controller/ib-controller#75]
After much hair tearing, I finally figured out that setting IBPassword= instead of IbPassword= was enough to cause the gateway not to start. No error message was logged that would have pointed this out to me either from what I was able to find.

Apologies for not including a PR with this report.. I am just not a Java guy.. Will leave this to those of you that know where to go looking.

**Comment by rlktradewright** [comment]
Well, I feel your pain, but there's not a lot that can be done about this. 

IBController loads the settings specified in the .ini file into a Java `Properties` object, which enables them to be accessed efficiently. This is basically a hash table where the setting names are used as the keys. Like any hash table, the keys are inherently case-sensitive.

So when it tries to fill in the password in the login dialog, it tries to retrieve the value using the key `IbPassword`, and if this value isn't defined (or the key is mis-spelled) it simply doesn't fill in that field, and doesn't attempt to complete the login. There is no question of an error message here, because it's part of the specification of `IbPassword` that if the value is not found, the user must complete the login manually. 

I could perhaps add a warning in the comments at the start of the specimen .ini file that emphasises the case-sensitive nature of the setting names.  

Actually, it's just occurred to me that it would be possible to convert all the names to, say, uppercase when loading the .ini file into the `Properties` object, and then upper-casing the name on any settings query, but this seems like a lot of work for something that has only ever been complained about once. Especially since the .ini file sample provided already contains all the names with their correct spellings...

**Comment by rterbush** [comment]
Fair enough and not to be read as a complaint.

Thanks again for your work maintaining this and your willingness to deal with the IB code base...
