### ISSUE TITLE
TWS version 955 is not installed

### ISSUE THREAD

**Issue by Plutarco** [ib-controller/ib-controller#76]
This is the first time I install the IB-Controller so I'm not sure what's wrong but I get the error message TWS version 955 is not installed.
The IBControllerStart.bat had it set to 954, so I changed it to 955 because recently I downloaded the latest version of TWS which is 955 and has been running manually in my machine since then.
All my directories are the default ones.
Isn't 955 supported yet?

**Comment by rlktradewright** [comment]
IBController does work with TWS 955, but there are some problems due to some of the changes IB have made in this release. I'm working on a new version that will make life smoother with 955.

Did you notice that you **must** use the offline download for use with IBController. It **does not work** with the version of TWS that you get to via the Logon box at the top of IB's home page. That is the most likely explanation for this message.

**Comment by Plutarco** [comment]
That solved the problem, thank you!
