### ISSUE TITLE
Made some changes to the source code, getting build failures for ant

### ISSUE THREAD

**Issue by the-entp** [ib-controller/ib-controller#77]
Hi,
I'm making changes to the source code and rebuilding it via
TWS=/usr/share/java/ib-tws ant clean dist

But the build fails:
BUILD FAILED
/opt/IBController/ib-controller-3.0.1/build.xml:21: Directory /opt/IBController/ib-controller-3.0.1/target/classes creation was not successful for an unknown reason

Also looking at the tws directory, I don't see where jts.jar is located.
I see these jar files
twslaunch.latest.jar
and jts.ini
but not jts.jar like the build.xml file says

Any ideas as to what could be going wrong?

**Comment by rlktradewright** [comment]
It looks like you're not using the offline download of TWS. 

IBController doesn't work with the self-updating version of TWS, nor can you build against it.

Once you've installed the correct download, jts.jar will be in ~/Jts/nnn/jars where nnn is the TWS major version number.

**Comment by the-entp** [comment]
Even the offline version does not have jts.jar in the jars. I am using version 955.

I only see these jars
jts4launch.jar, total.jar, twslaunch.jar, log4j-1.2.17.jar, twslaunch-install4j-1.4.jar

**Comment by rlktradewright** [comment]
Ok sorry, you're right. I just installed TWS 955 on my Ubuntu VM, and it seems that IB have changed things rather significantly in this version.

In fact TWS 955 is causing a lot of work for me, because it introduces quite a few changes that affect the way IBController works.

On Windows they hadn't changed the locations where files are installed, so until now I had just assumed that would be the case for Linux as well. My mistake, but one can't do everything at once.

However I now find that the latest install for 955 on Windows (dated 11 March) has also changed the jar files, so jts.jar no longer exists on Windows either!

It's probably just a case of discovering which of the various new jars contains the entry points for TWS and the Gateway, but it's Saturday and I don't propose to do it now!

Can I suggest you simply don't try to use TWS 955 until I've sorted this? Revert to the stable version (952).

**Comment by rlktradewright** [comment]
Ooops, I just realised that I got a bit confused with my previous post.

IBController itself still works with TWS 955.4g. The names of the jars are irrelevant to IBController as long as the jar containing the entry point is on the classpath, and the scripts ensure that is the case.

For building IBController, it should just be a case of setting your TWS environment variable to the directory that contains the jar files, ie 

`TWS=~/Jts/955/jars`

Actually what I do is keep a separate copy of the jar files in a directory with a fixed name, and set the TWS variable to it. You shouldn't need to update these jars when TWS is updated, because IB maintains backwards compatibility for the entry points.

**Comment by the-entp** [comment]
Hi Richard,
Thanks for responding on a Saturday.

I set TWS to TWS=~/Jts/955/jars, but I always get 

BUILD FAILED
/opt/IBController/ib-controller-3.0.1/build.xml:21: Directory /opt/IBController/ib-controller-3.0.1/target/classes creation was not successful for an unknown reason

I thought the build fail might be because it couldn't find a jts.jar

What do you think? I am using the offline version 955 of tws.

**Comment by rlktradewright** [comment]
You probably don't have write access to /opt/IBController/ib-controller-3.0.1/target/classes

Try building to a different output directory.

**Comment by the-entp** [comment]
Yup. That fixed the initial issue, but the build is still failing because IBController.java cannot find the jclient and ibgateway packages. Where are those located?

**Comment by rlktradewright** [comment]
Those packages used to be in jts.jar, but with the new arrangement I suspect they're in twslaunch.jar, but I haven't confirmed that. You can probably confirm it for yourself using the jar tool.

I'll get back onto this tomorrow.

**Comment by rlktradewright** [comment]
I was wrong. The missing packages are in jts4launch.jar. Hopefully you've already found this out for yourself.

So for the build to succeed, all you have to do is replace in build.xml this line:

`<pathelement path="${env.TWS}/jts.jar" />`

with this:

`<pathelement path="${env.TWS}/jts4launch.jar" />`

and make sure the TWS environment variable points to the directory containing jts4launch.jar.

**Comment by the-entp** [comment]
Thanks! That works.

**Comment by jacktang** [comment]
I suggest the external.classpath in build.xml should look like this:

    <path id="external.classpath">
        <fileset dir="${env.TWS}" includes="**/*.jar"/>
    </path>

**Comment by rlktradewright** [comment]
Yep, thanks, definitely cleaner. Done, hopefully commit with other changes later today.
