### ISSUE TITLE
IB-Controller ShowAllTrades forces Trades window

### ISSUE THREAD

**Issue by DxCx** [ib-controller/ib-controller#82]
Hi,

I'm trying to use the ShowAllTrades options, so the API will have the order's history,
however, when set, the TWS UI pops up a Trades window, which cannot be closed (Closing it invokes recreation of the window)

I'm using TWS 955.4m along with IBController-v3.0.1

**Comment by rlktradewright** [comment]
I've already referred to the fact that you shouldn't be using IBController 3.0.1 with TWS 955.4m in #80.

However it's worth pointing out that IB have changed how the Trades window works in TWS 955, so that the previous workaround that IBController did when you set ShowAllTrades=yes no longer works, and indeed is no longer necessary - you can now configure the Trades window to show all orders and that setting is now persisted across sessions. You have to do this manually because I can't find a way to do it in code.

With earlier TWS versions where ShowAllTrades=yes works, IBController automatically re-opens the Trades window and re-sets all the checkboxes if the user closes it: this prevents the user manually unchecking them, and is also necessary because those checkbox settings only apply while the Trades window is actually open.

The new version of IBController that works properly with TWS 955 will behave somewhat differently: I haven't finalised it yet, but it will probably fail to start if ShowAllTrades=yes when TWS 955 or later is in use, to ensure the user understands that this setting no longer works.

**Comment by rlktradewright** [comment]
The new version of IBController that supports TWS 955 is now available (Release 3.2.0-beta.1).

This new version ignores the `ShowAllTrades` setting when running TWS 955, apart from logging a message in the TWS log file. For earlier TWS versions the behaviour is as before.

It is up to the user to configure the new options in the Trades window as required. Make sure you do this before running any API programs that depend on execution details from previous sessions being returned.
