### ISSUE TITLE
New User on IBControllerStart.bat issue

### ISSUE THREAD

**Issue by clarkys** [ib-controller/ib-controller#83]
Hi,

I followed the User Guide for the latest IBController and made sure all the settings were done accordingly. However, when I double-clicked IBControllerStart.bat, only a command prompt screen flashes for a fraction of a second, nothing else happened... TWS 952 did not get started... Can someone please help?

thanks,
Clark

**Comment by TimboMachimbo** [comment]
Thank you! I've been experiencing the same issues. I was about to dedicate an afternoon to fixing it but it seems like the issue lies with the code & not user setup.

**Comment by rlktradewright** [comment]
The first thing is to make sure you’re using the OFFLINE version of TWS, not the self-updating version.

 

If you are, then instead of double-clicking on IBControllerStart.bat, do the following which will enable you to see more easily what’s gone wrong:

 

In Windows Explorer hold down the shift key and right-click on the IBController folder. Select ‘Open command window here’. Now type IBControllerStart.bat at the command prompt and press enter. 

 

Now report what happens.

**Comment by rlktradewright** [comment]
Well I’m sorry to disappoint you Mr Miller, but when IBController fails to start it is always because of incorrect setup, not the fault of the IBController code.

 

See my response to the original poster.

**Comment by clarkys** [comment]
Thank you, rlk! I'll report back ASAP!

**Comment by clarkys** [comment]
Hi rlktraderwright,

I followed your instructions and it worked!!! Thanks a million!!! You're the BEST!!!

Clark

**Comment by TimboMachimbo** [comment]
Apologies rlktradewright, I did not mean to come off as such a dick. I appreciate your work on IB-Controller and it works properly on my system. Good work!
