### ISSUE TITLE
Usage of IBController-3.2.1-beta.1

### ISSUE THREAD

**Issue by DxCx** [ib-controller/ib-controller#91]
Hi,

First of all, running IBController.sh script on linux errors out on line 94, because of the space on OS X.
This is something i solved locally.

However, when i tried to redownload and install the tws-offline installer, i now get TWS 956 instead of 955.
IBController is not yet compatible with 956. (Looks like there is a string that was changed)
how can i obtain the offline installer for tws 955 again so i can test the new IBController version?
or, alternatively, is there a plans to support tws 956 any time soon?

**Comment by rlktradewright** [comment]
I’m sorry about this. The error on line 94 was something I had noticed during my testing and then forgot to track down in my rush to get things out the door last Friday (I was going away for the weekend – you’d think after 41 years of developing software, I’d know not to release anything under time pressure: always better to be late than wrong!). Actually it doesn't seem to stop IBController working on my Ubuntu system: just an extraneous error message in the logfile.

Regarding TWS 956, I was hoping that IB wouldn’t make 956 the latest version for a while yet, because I had a little play with it a few weeks ago and thought then that it was going to involve another bunch of work on my part, but they’ve caught me on the hop.

I have a copy of the Linux TWS 955 that I’m just uploading to my OneDrive. It’ll probably take a while to complete, because my uplink speed is a bit slow, but when it’s done it’ll post a link.

I'll take a look at TWS 956 shortly to assess what needs to be done. Hopefully it won't be too long before I can release a new version of IBController to support it.

**Comment by rlktradewright** [comment]
The upload has completed and the link is:

[tws-latest-standalone-linux-x64.sh](tps://onedrive.live.com/redir?resid=599F0C96432C9F5A!94289&authkey=!AMDnX8-G1Ffl3aQ&ithint=file%2csh)

**Comment by rlktradewright** [comment]
I just tried running TWS 956 and it seems to run perfectly. Can you please tell me what didn't work when you tried it?

**Comment by DxCx** [comment]
Hi richard thanks for the prompt response

Ill try the tws 955 later.
On tws 956 it wont login, it is looking for the string store settings on server but looks like to me they renamed it to migrate settings something
Then there is an internal exception being handled but it stops the login procedure..

Later i can post it more exactly

**Comment by DxCx** [comment]
Ok,

so now i'm in front of a computer,
as for TWS 956, This is the error i'm receiving:
12:23:57:405 IBController: could not login: could not find control: Use/store settings on server

When checking the UI, this checkbox is no longer exists.
This is how the window is at the moment:
http://imgur.com/EeEZS8Cl.png

Next, i've taken beta.2 release, with the TWS 955 you've provided,
and it works well as expected :)

P.S
i'm working with set -e on my scripts, that's why you didn't not the OS X :)

**Comment by rlktradewright** [comment]
Interesting, my login dialog looks like this (this is Windows, but it's exactly the same on Ubuntu):

![tws956login](https://cloud.githubusercontent.com/assets/7384655/15323979/60a94d40-1c3c-11e6-9a4b-5276d6d67df4.PNG)

I think what's going on here is that either you've installed TWS to /opt/IBJts, or you've set IbDir=//opt//IBJts, and this is probably not writeable, so it doesn't allow you the option of not storing the settings on the server.

Can you please make sure the TWS settings folder is writable, and see if that resolves the problem.

**Comment by DxCx** [comment]
Hi,

this is the output of ls command, looks ok to me:
/ # ls -al /opt/IBJts/
total 228
drwxr-xr-x    6 root     root          4096 May 17 19:41 .
drwxr-xr-x    9 root     root          4096 May 17 19:40 ..
drwxr-xr-x    2 root     root          4096 May 17 12:46 .install4j
-rwxr-xr-x    1 root     root           180 May 17 12:46 Trader Workstation 955.desktop
lrwxrwxrwx    1 root     root            22 May 17 19:40 dgmgqticxk -> /ib-configs/dgmgqticxk
drwxr-xr-x    2 root     root          4096 May 17 19:40 jars
-rw-r--r--    1 root     root           221 May 17 19:41 jts.ini
-rw-r--r--    1 root     root         14501 May 17 19:40 launcher.Tue.txt
-rw-r--r--    1 root     root         96072 May  6 14:28 locales.jar
-rw-r--r--    1 root     root         24636 May 17 19:41 log.Tue.txt
-rwxr-xr-x    1 root     root         11999 Apr  4 11:14 tws
-rw-r--r--    1 root     root           716 May 17 12:46 tws.vmoptions
-rwx------    1 root     root         12339 Apr  4 11:14 uninstall
-rw-r--r--    1 root     root         29608 May 17 19:41 xmlopt.dat
/ # ls -al /opt/IBJts/ls -
/ # ls -al /ib-configs/dgmgqticxk
total 7288
drwxr-xr-x    4 root     root          4096 May 17 19:41 .
drwxr-xr-x    3 1000     users         4096 May 17 19:40 ..
-rw-r--r--    1 root     root          2905 May 17 19:41 Tue.audit.xml
-rw-r--r--    1 root     root           119 May 17 19:41 ad.dat
-rw-r--r--    1 root     root           176 May 17 19:41 ad.locator
drwxr-xr-x    2 root     root          4096 Apr 19 10:40 cheatsheets
lrwxrwxrwx    1 root     root            22 Apr 19 10:42 dgmgqticxk -> /ib-configs/dgmgqticxk
-rw-r--r--    1 root     root       3494583 May 12 10:36 language.jar
-rw-r--r--    1 root     root        132434 May 17 12:47 loadscreen_benchmarker.png
-rw-r--r--    1 root     root         56495 Apr 19 10:40 loadscreen_sdsa.png
-rw-r--r--    1 root     root            16 May 17 19:41 nia2.lck
-rw-r--r--    1 root     root            42 May 17 19:41 nia2.log
-rw-r--r--    1 root     root            85 May 17 19:41 nia2.properties
-rw-r--r--    1 root     root            85 May 17 19:41 nia2.properties.bak
-rw-r--r--    1 root     root          2143 May 17 19:41 nia2.script
-rw-r--r--    1 root     root          2143 May 17 19:41 nia2.script.bak
drwxr-xr-x    2 root     root          4096 Apr 19 10:40 nia2.tmp
-rw-r--r--    1 root     root            10 May 17 19:41 seqNum.dat
-rw-r--r--    1 root     root       1794983 Apr 19 11:07 tws.tmp.xml
-rw-r--r--    1 root     root       1916251 May 17 12:47 tws.xml

The only thing that i can think of is that i have link to the user configure directory,
and this is because i'm running TWS as a VNC-TWS Docker, and i want the configuration to be on a volume.

**Comment by rlktradewright** [comment]
It's not clear to me why running in a Docker means you need to configure anything differently from usual, but I have little knowledge of Docker.

Is there any reason why you can't just set 

IbDir=//ib-configs

in IBController, rather than using your link?

**Comment by DxCx** [comment]
Hi,

Ok, my docker have some base configuration that is the "default"
and it's being written on the initial run of the docker.
then, the configuration is managed on a volume, because if some config is changed on runtime, i want to keep it. (For example, enabling API gateway which i couldn't find an option for)

but, it doesn't really matter as i finally had the time to check this behavior for you,
even if the ibDir is set as you mentioned (Configuration files are copied there), i still see the same behavior.

**Comment by rlktradewright** [comment]
I've finally discovered what's going on here, after a lot of experimentation and tearing my hair out.

There is a file called jts.ini which must be in the TWS/Gateway settings folder, and this contains various settings that govern certain aspects of TWS/Gateway's operation which are not account-dependent (for example the colour scheme).

Now, starting with TWS 952, TWS consists of several Java jar files where there used to be only one. The old single jar file, which was called jts.jar, is now replaced by jts4launch.jar: this latter jar is the only one that IBController 'knows' about, and it contains the main entrypoints into both TWS and the Gateway. The additional jar files are invoked when you run TWS from the installed shortcuts: I don't know the full extent of what they do, but they certainly contain the auto-updating mechanism that's used by the non-standalone TWS versions. 

In TWS 956,  jts4launch.jar only displays the `Use/store settings on server` field in the Login dialog if jts.ini exists and contains at least the following:

```
[Logon]
s3store=true
```

This is different from TWS 952, where jts4launch.jar will display the `Use/store settings on server` field even if jts.ini does not exist. 

For both versions, a successful logon results in a full jts.ini with lots of settings being created.

Now, when you run TWS from the shortcuts, it does preliminary processing before it enters jts4launch.jar, and in the case of TWS 956 that includes creating a minimal jts.ini with the contents shown above (plus a bit more) if it doesn't already exist. (TWS 952 doesn't do this since its jts4launch .jar doesn't care if jts.ini doesn't exist.)

So now, if you use IBController to run TWS 956 on a machine that doesn't have a jts.ini with the lines shown above in the appropriate place, then the `Use/store settings on server` field in the Login dialog is not displayed, and IBController logs an error. It then sits with the login dialog on display but without the username and password (because it hasn't entered them at this point).

By the way, it's worth pointing out that if you're running the Gateway rather than TWS, there is no problem because IBController doesn't try to reference the `Use/store settings on server` field during Gateway logon.

The immediate workaround for this issue is to either: a) run TWS or the Gateway once from the installed shortcuts, or b) use IBController to run the Gateway: either will cause an adequate jts.ini to be created, or c) create a jts.ini file containing the lines shown above in the settings folder.

To fix this in the short term, I propose to do the following:

1. Before IBController calls the TWS entrypoint, it will check for the existence of a jts.ini containing at least the above lines in the TWS settings folder.

2. If no such file is found, it will create a minimal jts.ini as shown above.

3. If a jts.ini is found that doesn't contain the required entries, it will be modified to include them.

In the longer term, it may be possible to enter IB's code at an earlier point than currently, so that all the functionality included in the additional jars (whatever it is!) is invoked. That might then allow the self-updating versions of TWS to be used, for those who feel brave enough to risk it! However the investigations I've done so far haven't succeeded in finding the appropriate entrypoint.

**Comment by DxCx** [comment]
Confirmed to be working well: TWS 956 + IBController 3.2.0.

Thank you very much, i really appreciate your hard work! :+1:

**Comment by trade-commander1** [comment]
Hello poeple, thank you for your work in particular for rlktradewright  who sheld light into the startup problems with version 952. 
Version 952 is still IBs actual stable version (which i do recommend my customers).
Based on your investigations i figured out that a  jts.ini file
with this minimal content
[Logon]
Locale=en
makes TWS 952 starting  with IBController 3.2.0
Just want to share this
