### ISSUE TITLE
3.2.0-beta.2 doesn't run on Mac OS X

### ISSUE THREAD

**Issue by brian-from-quantrocket** [ib-controller/ib-controller#94]
I had to make several changes to the shell scripts to get them to run on Mac OS X El Capitan. 

In `IBControllerGatewayStart-OSX.sh`, the variable `MODE` is used to specify TWS or GATEWAY, but it should be `APP`. The Linux scripts use `APP`, looks like the Mac scripts just didn't get updated.

I ran into two issues with `DisplayBannerAndLaunch.sh`. First, the `-r` flag for `date` is not available on Mac. I believe the `stat` command shown below in the diff is cross-platform. Second, I was getting this error: `line 46: ${APP^^}: bad substitution`. I'm not sure what the double caret is for, but I resolved the problem by getting rid of it.

``` bash
$ diff Downloads/IBController/Scripts/DisplayBannerAndLaunch.sh IBController/Scripts/DisplayBannerAndLaunch.sh 
10c10
<   

---
> 
20c20
<       if [[ $(date -r "$log_file" +%D) != $(date +%D) ]]; then rm "$log_file"; fi

---
>       if [[ $(stat -f "%Sm" -t %D "$log_file") != $(date +%D) ]]; then rm "$log_file"; fi
46c46
< if [[ "${APP^^}" = "GATEWAY" ]]; then 

---
> if [[ "${APP}" = "GATEWAY" ]]; then

```

Finally, not a bug but a tip for any Mac users that want to use launchd to run these scripts: I had to change the last line of `IBControllerGatewayStart-OSX.sh` not to run in the background (i.e. delete `&`): 

``` bash
151c153
< "${IBC_PATH}/Scripts/DisplayBannerAndLaunch.sh" &

---
> "${IBC_PATH}/Scripts/DisplayBannerAndLaunch.sh"
```

**Comment by rlktradewright** [comment]
@brianjaystanley 

Thanks for the feedback.

You're right about the `MODE` variable: this was sloppiness on my part!

The ^^ construct on Bash 4 converts the variable's value to upper case. Sounds like OS X doesn't have that version yet?

I guess I'll have to do something like this:

`if [[ "$(echo ${APP} | tr [:lower:] [:upper:])" = "GATEWAY" ]]; then ...`

but it's rather clumsy.

Regarding background running, it might be worth explaining that what I really wanted to do was something similar to the Windows scripts, which run the banner display in a separate shell window, so that the launching shell can continue without losing the banner display (which contains information about the log file). On Linux I managed to do this reasonably well with an `xterm`  command, but I couldn't ascertain whether this would work on OS X (not having access to a Mac makes life awkward when doing this sort of thing!). So I opted for running `DisplayBannerAndLaunch.sh` in background, because as long as the user doesn't close the launching shell the banner is still visible by scrolling back; and if the user does close the launching shell, at least IBController keeps running (whereas running the whole `IBConrollerStart.sh` in background kills IBController if the user exits the launching shell).

I'll issue an updated release in due course (I'm supposed to be 'on leave' this week so I'm not really sitting at the computer at all at the moment...).

**Comment by brianjaystanley** [comment]
Correct, OS X still has bash 3.2.x, possibly because of license issues: https://blog.bennycornelissen.nl/bash-4-x-on-osx-the-bash-that-apple-wont-ship/

**Comment by rlktradewright** [comment]
@brianjaystanley the stat command you gave doesn't work on Linux, so I'll check the operating system and use it for OS X and the original one for Linux.

**Comment by kamzik7** [comment]
Thank you for the fixes. It looks like the fix is incomplete - variable 'APP' is now set but not exported, so IBControllerGatewayStart-OSX.sh still starts TWS instead of Gateway and IBControllerStart-OSX.sh sets wrong log file location:  .../Logs/ibc-3.2.0_-956_Sunday.txt
while we expect: .../Logs/ibc-3.2.0_TWS-956_Sunday.txt

Attached is a patch with a proposed fix (export APP and check that APP is set in DisplayBannerAndLaunch.sh)

[ibc.patch.zip](https://github.com/ib-controller/ib-controller/files/344990/ibc.patch.zip)
